### ISSUE TITLE
Remove Html Wrapper

### ISSUE THREAD

**Issue by ericrange** [Polymer/vulcanize#109]
is it possible to avoid that vulcanize wraps the build with a html wrapper? so that i just get the vulcanised part and not the ```<doctype html>... </html>```

that would be VERY VERY usefull to dynamic websites... you could exclude the "imports" in an extra file which is then "vulcanisable" ;)

**Comment by Porta** [comment]
+1 on this one.

**Comment by doug** [comment]
:+1:

**Comment by azakus** [comment]
This gist with the `dom5` module can accomplish this: https://gist.github.com/azakus/dfc442589a9bd934070b
