### ISSUE TITLE
vulcanize inline doesn't work with webcomponents.js

### ISSUE THREAD

**Issue by ebidel** [Polymer/vulcanize#113]
_From @elsigh on December 4, 2014 20:1_

https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents.js#L88

when vulcanize is inlining, there is no script tag yet in the dom for this to work against.

_Copied from original issue: webcomponents/webcomponentsjs#86_

**Comment by rlancer** [comment]
Getting this issue as well as Uncaught TypeError: undefined is not a function on "scope.CoreResizer = Polymer.mixin({"

**Comment by jshado1** [comment]
+1
