### ISSUE TITLE
vulcanize converts &deg; to °, which renders incorrectly in the browser

### ISSUE THREAD

**Issue by kaldrenon** [Polymer/vulcanize#124]
Given the following markup in a source file:

    <span class="symbol">&deg;</span>

I get the following markup in my vulcanized application:

    <span class="symbol">°</span>

In the browser (tested in Chrome and Firefox), it renders like this:

![](http://i.imgur.com/DOJAmtb.png)

I am using `vulcanize 0.7.5` via `gulp-vulcanize`, and I have confirmed that the effect occurs whether I `inline`, `strip`, both, or neither.

**Comment by trumant** [comment]
Including ```<meta charset="utf-8">``` in the document head corrects the issue in Chrome and Firefox.

**Comment by drewp** [comment]
Thanks for the workaround, trumant. I was seeing it with "&#128263;" in my source, and I would not expect vulcanize to alter that text (nor &deg;) as part of its work.

**Comment by azakus** [comment]
Vulcanize sets the UTF-8 charset on all output in 1.x
