### ISSUE TITLE
vulcanize on ubuntu

### ISSUE THREAD

**Issue by Kleak** [Polymer/vulcanize#125]
vulcanize do nothing on my ubuntu 14.04 LTS
and end with no error

**Comment by cdata** [comment]
Can you provide us with a few more details about how you are trying to use Vulcanize? I can spin up an Ubuntu instance and try to reproduce.

**Comment by Kleak** [comment]
all commands not work :/ 
as well just vulcanize -V until vulcanize -o build.html index.html --inline --csp

**Comment by azakus** [comment]
Can you provide a sampling of the input files and the commands you ran on them?

**Comment by cdata** [comment]
@Kleak I'm unable to reproduce the issue with the information you've provided. On a fresh Ubuntu 14.04 machine, I have successfully used the command `vulcanize -o build.html index.html --inline --csp` to generate the build.html and build.js for Polymer's TodoMVC example.

**Comment by Kleak** [comment]
ok it's the node binary which is not working (why i don't know), with the nodejs binary it's work sorry for the disturbing
