### ISSUE TITLE
Form closing tag is moved to the end of the template

### ISSUE THREAD

**Issue by hubgit** [Polymer/vulcanize#127]
When vulcanizing (v0.7.6), the closing tag of a form is moved to the end of the template.

## input.html

```html
<polymer-element name="x-foo" noscript>
  <template>
    <form><input name="q"></form>
    <div>a div</div>
    <span>a span</span>
  </template>
</polymer-element>
```

## vulcanized.html
```html
<html><head></head><body><polymer-element name="x-foo" assetpath="">
  <template>
    <form><input name="q">
    <div>a div</div>
    <span>a span</span>
  </form></template>
<script>Polymer('x-foo');</script></polymer-element></body></html>
```

**Comment by hubgit** [comment]
This is working correctly in v0.4.3, and moves the closing tag in v0.5.0 onwards.

**Comment by hubgit** [comment]
[Reported upstream in parse5](https://github.com/inikulin/parse5/issues/40), as it's due to the recently-added support for `<template>` there.

**Comment by inikulin** [comment]
Fixed in parse5 and whacko.

**Comment by errows** [comment]
When can this be released?

Thanks
