### ISSUE TITLE
Too many HTTP requests for JS files, even after Vulcanizing

### ISSUE THREAD

**Issue by richieb** [Polymer/vulcanize#128]
I noticed that after I vulcanized my app, the app still has to make about six separate HTTP requests to download some JS files.

Why doesn't Vulcanize concatenate, uglify, and minify (routine build steps for JavaScript web development nowadays) all the JS files? Do we have to use vulcanize along with Gulp or Grunt?

**Comment by ebidel** [comment]
Vulcanize is a tool to crush HTML Imports. It does, however, have a feature that inlines JS/css files inside the crushed import. 

If you run vulcanize with the `--inline` flag, it will pull the .js files into your vulcanized html import. That'll save you those requests.

**Comment by richieb** [comment]
Thanks, Eric. That works. 

Vulcanize wasn't kidding when it said "inline"; it inlined everything, including toenails and fingernails.

**Comment by ebidel** [comment]
Head, shoulders, knees, and toes! Closing :)

**Comment by richieb** [comment]
Hehe. 
One note: Since a Polymer production site will have just the single, chunky, vulcanized file, the need for a paper **preloader** element has become more apparent. I specifically mentioned *paper* because the preloader should be at least as lovely as the best material design paper elements.
