### ISSUE TITLE
Style display none being shown

### ISSUE THREAD

**Issue by rlancer** [Polymer/vulcanize#133]
After upgrading vulcanize items styled as display none started to show up. It appears to be very prevalent when using the style attribute.

**Comment by azakus** [comment]
Can you provide some more info?

An example bit of code you see this occur with would be a great help.

**Comment by rlancer** [comment]
<div style="display: none;width:220px;background-color:#fefefe;border-left: 1px solid #eee" class="scroll">
 Content should be hidden but its show with the new update ... 
      </div>

**Comment by rlancer** [comment]
Just ran a more in depth test ... 

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Vulcanize test</title>
</head>
<body>
<div style="display: none;">Should be hidden!</div>
</body>
</html>
```

Converts to 

```
<!DOCTYPE html><html><head>
  <meta charset="UTF-8">
  <title>Vulcanize test</title>
</head>
<body>
<div style="display:%20none;">Should be hidden!</div>


</body></html>
```

**Comment by rlancer** [comment]
Ran another test 

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Vulcanize test</title>
</head>
<body>
<div style="display: none;" title="Hello this is a test">Should be hidden!</div>
</body>
</html>
```

Converters to 

```
<!DOCTYPE html><html><head>
  <meta charset="UTF-8">
  <title>Vulcanize test</title>
</head>
<body>
<div style="display:%20none;" title="Hello this is a test">Should be hidden!</div>

 

</body></html>
```

So it appears to be URL encoding the style attribute improperly but not other attributes. 

For each of these the vulcanize command was run with only the output parameter.

**Comment by AEtherSurfer** [comment]
I am seeing this as well.  vulcanize will randomly url encode style attributes. Not all style attributes just some of them.  It looks like it treats style tags with binding params normally.  That might be a workaround.

**Comment by AEtherSurfer** [comment]
<div style="background-color: green;">Green
        <div style="color: red; border: {{test}};">Red</div>
        <div style="color: orange;">Orange</div>
    </div>

becomes 

    <html><head></head><body><div style="background-color:%20green;">Green
        <div style="color: red; border: {{test}};">Red</div>
        <div style="color:%20orange;">Orange</div>
    </div>
    </body></html>
