### ISSUE TITLE
Vulcanize breaks my anchor tag hrefs

### ISSUE THREAD

**Issue by AminElNaggar** [Polymer/vulcanize#135]
I have a simple `<a href="mailto:some@email.com">Dont Vulcanize me bro</a>` and after running vulcanize I end with this hot mess `<a href="some-web-component/mailto:some@email.com">Dont Vulcanize me bro</a>`

How do I make it stop looking into my anchors? or what syntax could I use to help it skip?

**Comment by azakus** [comment]
This should be working as of at least 0.5. What version of vulcanize are you using?

**Comment by AminElNaggar** [comment]
@azakus You're right I had `vulcanize` in a `dev` section in my `project.json` so everyime I ran npm update it would hit regular `dependencies` and not `devDependencies`

After I checked it seems like I was at version 0.3 ....yikes lol.

Thanks for the help
