### ISSUE TITLE
Inlining scripts with type `application/javascript`

### ISSUE THREAD

**Issue by kdabir** [Polymer/vulcanize#137]
Most likely while fixing #11, the script check became more strict such that it now doesn't inline scripts marked with `type="application/javascript"`. It took me some time to figure out since some of our script tags were written like:

    <script type="application/javascript" src="path/to/script.js"></script>

To fix it, [this line](https://github.com/Polymer/vulcanize/blob/master/lib/constants.js#L11) can be updated to 

    var JS = '$('script:not([type]), script[type="text/javascript"], script[type="application/javascript"]')';

Instead of sending PR, I am raising an issue as I am not sure whether this exclusion a deliberate or unintentional. If it is deliberate, then it should be documented somewhere. Either ways this issue might help someone else's few hours in future.

**Comment by azakus** [comment]
@kdabir Nope, that was unintentional.
