### ISSUE TITLE
Not include javascript script within .html export

### ISSUE THREAD

**Issue by reggi** [Polymer/vulcanize#138]
I'm running this command

```bash
vulcanize ./polymer/fold-over.html --inline --csp vulcanize.js
```

And I have this in the last line of my `vulcanize.html file`.

```html
<script charset="utf-8" src="vulcanized.js"></script>
```

I need to remove that script tag from the export.

**Comment by reggi** [comment]
I made something to strip a doc of `<script>` tags. 

https://github.com/reggi/node-rmscripts

Feel free to close if not essential to vulcanize.

**Comment by azakus** [comment]
Why are you removing the script tag? It contains the script you had in your import. Without it, any elements in your import will probably fail to work.

**Comment by azakus** [comment]
Is this related to #139?

**Comment by reggi** [comment]
Yes and No. I'm using a host that sets up their own assets. (Shopify)
I need a way to point to my assets in the theme directly.

```
<link rel="import" href="{{ polymer-components.html | assets_url }}">
<script src="{{ polymer-components.js | assets_url}}"></script>
```

That link is a server-side variable that links tho their CDN. 
I'd imagine wordpress themes would need the same kind of support.

**Comment by reggi** [comment]
Works! I get it `--strip` is a function of uglify, which doesn't understand es6 syntax. Thanks for the help @azakus!!
