### ISSUE TITLE
No ES6 support

### ISSUE THREAD

**Issue by reggi** [Polymer/vulcanize#139]
I simply have `import moment from "moment"` within my component and i get this error.

```
    at compressJS (/Users/thomas/.nvm/v0.10.32/lib/node_modules/vulcanize/lib/vulcan.js:191:18)
    at Object.handleMainDocument [as processDocument] (/Users/thomas/.nvm/v0.10.32/lib/node_modules/vulcanize/lib/vulcan.js:313:23)
    at /Users/thomas/.nvm/v0.10.32/lib/node_modules/vulcanize/bin/vulcanize:109:10
    at /Users/thomas/.nvm/v0.10.32/lib/node_modules/vulcanize/lib/vulcan.js:37:5
    at Object.processOptions (/Users/thomas/.nvm/v0.10.32/lib/node_modules/vulcanize/lib/optparser.js:101:3)
    at Object.setOptions (/Users/thomas/.nvm/v0.10.32/lib/node_modules/vulcanize/lib/vulcan.js:32:13)
    at Object.<anonymous> (/Users/thomas/.nvm/v0.10.32/lib/node_modules/vulcanize/bin/vulcanize:104:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by azakus** [comment]
If you're using `--strip` option, that is passed through uglifyjs, which may or may not support ES6 import syntax.

However, I believe the ES6 Module Loader does not actually exist in a browser yet, so I'm not sure what utility you'll get from leaving the "import" line in the browser.

If you're using a transpiler, you can have a temporary file available that is the es5 output and use that in your import instead.

**Comment by reggi** [comment]
I'm trying to `import` browseify dependancies within the component export all the javascript from a component with vulcanize then convert the es6 into es5 (transpile) then browserify the whole thing.

What am I doing wrong? I just need vulcanize to extract all the javascript and put it into one file.

**Comment by azakus** [comment]
I think you might be able to accomplish this with `--inline --csp`, then process the output file. The `--strip` option seems to be your only obstacle there.

**Comment by lastmjs** [comment]
@reggi Do you have a solution for this in the current version of vulcanize? The API seems to have changed, and when I do `--inline-scripts`, and my scripts have imports, I get:

```
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'
```

Have you had a similar problem?

**Comment by reggi** [comment]
@lastmjs Sorry, nope totally gave up on this project :/

**Comment by boldfacedesign** [comment]
@lastmjs did you find a solution to the sourceType: module issue? 
@azakus would it be possible to tell vulcanize to simply ignore es2015 imports?  via a flag or option. Then we can do any necessary bundling/transpiling ourselves later.

**Comment by svantetobias** [comment]
I have the same issue :-/ Any help is very welcome.
