### ISSUE TITLE
Add flag to change which folder is the "base" for -o, input or output

### ISSUE THREAD

**Issue by azakus** [Polymer/vulcanize#14]
Default will be "input", add `-r` or `--rel-to-output`

**Comment by kincaidoneil** [comment]
:+1:
What's the status of this...? I'd certainly find it very useful!

**Comment by pflannery** [comment]
:+1: I need the base path to be based on my output path

if I have ```vulcanize -o dist/index.html app/index.html``` I end up with paths beginning with ```../app``` or if I use ```--abspath .``` I end up with paths beginning with ```/```, neither of these are desirable for my situation...

**Comment by azakus** [comment]
This bug is no longer relevant. As of 1.0, vulcanize allows for custom file loaders and returns text instead of writing files.
