### ISSUE TITLE
Vulcanize is breaking a font or font rendering.

### ISSUE THREAD

**Issue by PudgePacket** [Polymer/vulcanize#143]
After I run my site through vulcanize one of the titles doesn't render correctly. It goes from Japanese text to jibberish. Only this title is affected though. What information would you like from me to diagnose this?

Pre-vulcanize: http://i.imgur.com/QLpAooG.png
Post-vulcanize: http://i.imgur.com/swIabhU.png

**Comment by azakus** [comment]
Do you have a "charset=utf-8" in your source or headers?
HTML Imports are automatically utf-8, but you may be missing that directive in the inline version.

**Comment by PudgePacket** [comment]
Thanks, that fixed it!
