### ISSUE TITLE
fit and safari

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/vulcanize#145]
(link expired)

Why does vulcanize messes up safari again? It does work in chrome?

Let me know if you can reproduce it, its a production site so the link is temporary.

**Comment by ragingwind** [comment]
Did you check the console messages in the inspect of safari?

**Comment by gertcuykens** [comment]
yes but that does not make sense because I do use fit, and I do not have the error message when it is not vulcanised. Also chrome is not complaining, it should also show this error message if that was the case.

**Comment by gertcuykens** [comment]
closing this for now just note that fit inside a vulcanised element breaks core-list in safari only.
