### ISSUE TITLE
Vulcanize breaks when you include a directory (with index file) 

### ISSUE THREAD

**Issue by pcvandamcb** [Polymer/vulcanize#157]
With imports you can have a directory and include an index.html file, like this:

    <link rel="import" href="elements/elementgroup" />

If that directory contains an index.html, it will load that. Vulcanize breaks on this giving:
Error: EISDIR, illegal operation on a directory

**Comment by azakus** [comment]
Vulcanize doesn't have any auto-indexing capability, so this is expected.
I'm concerned that trying to add this behavior will add a long-tail of confusing bugs, so I'm not inclined to implement it.
