### ISSUE TITLE
[1.2.1] Using --inline-scripts and --exclude 

### ISSUE THREAD

**Issue by frasator** [Polymer/vulcanize#158]
I have excluded a path containing a js script, and combined with -inline-scripts.
The html file generated contains:  <script></script>, I think this is wrong because that line does nothing.
I expected vulcanize to do nothing with that line, it just removed the src attribute.

Thanks!

**Comment by azakus** [comment]
This seems somewhat minor, so I'll put it on the backlog for general cleanup.

**Comment by garlicnation** [comment]
This seems potentially really serious.

PR: https://github.com/Polymer/vulcanize/pull/178
