### ISSUE TITLE
base target is not kept

### ISSUE THREAD

**Issue by AEtherSurfer** [Polymer/vulcanize#161]
`<base target="_blank"/>`

I think https://github.com/Polymer/vulcanize/issues/94 caused vulcanize to drop the `base` tag altogether even if it has a `target` attr.  It should keep the base tag with just the `target` attr if the `target` attr is present.

**Comment by azakus** [comment]
I didn't even know about `<base target>`!

**Comment by shannonmpoole** [comment]
This also breaks angular html5 mode.

https://docs.angularjs.org/error/$location/nobase

There is also some confusion about using something like 

```
<base href="/'>
<link rel="manifest" href="manifest.json">
```

I'm not sure but I think Vulcanize seems to take everything from the root of the system. I end up with a link like this and nothing concatenated.

```
<link rel="manifest" href="../../../../../../.index.html/manifest.json">
```

**Comment by hawkett** [comment]
With a folder structure like:

```
/foo
   /index.html
/bar
   /my-element.html
```

URL in the address bar is ```/foo/index.html```

index.html specifies:
* ```<base href="/foo/" target="_blank">```
* ```<link rel="import" href="../bar/my-element.html">```

This works fine in Chrome/Firefox/Safari without vulcanization, but breaks during vulcanization with: ```Error: ENOENT, open '/foo/bar/my-element.html'```

The reason for doing this in my case is that I want *any* path beginning with ```/foo/``` (e.g. ```/foo/users/1/profile```) to serve up index.html, and I then use page.js *without hashbang* to treat ```users/1/profile``` as a route in my SPA. Without the ```<base>``` tag, the actual base will vary with whatever the path is when index.html is served up.

Worth noting that the href attribute in ```<base>``` [must be absolute](http://www.w3.org/TR/html-markup/datatypes.html#common.data.uri.absolute-def) - so the href in the original post is not technically valid as far as I read it.
