### ISSUE TITLE
Update NPM Registry Package to latest (please?)

### ISSUE THREAD

**Issue by adewinter** [Polymer/vulcanize#163]
Currently, NPM lists the Vulcanize version as 0.7.10.   Master is (as of this writing) on version 1.2.1.

Could NPM be updated to point to the newest version?

**Comment by azakus** [comment]
vulcanize 1.2.1 is available with the `polymer-0.8` tag

    npm install vulcanize@polymer-0.8

After polymer 0.8 is released, then I will flip the tags to make the 1.x branch default.
The reason for this is that vulcanize 0.7.x works only with Polymer 0.5, and vulcanize 1.x works only with Polymer 0.8.

**Comment by adewinter** [comment]
Gotcha.   I wonder if it's worth it at this point to update the README or something?  Happy to write something up if you're down.

Thanks for the info!

**Comment by azakus** [comment]
Now that Polymer 0.9.0 is released, vulcanize 1.4.3 is released as the latest version.

**Comment by LeondidV** [comment]
Hello azakus! Help me!
I am a beginner of polymer programmer.
I have a problems. I had a polymer program.
But I can't build that. During building, following errors are tracked.
"This version of vulcanize is not compatible with Polymer<0.0. Please use vulcanize 0.7.x.
File: d:\JSFramework\source\example-element\masterFrame-element.html".
I don't understand that. Of course, I did following your suggestion.
But the error is still checked. I hope your help.
Best regards.
Leonid.
