### ISSUE TITLE
inlining script not working

### ISSUE THREAD

**Issue by benjiec** [Polymer/vulcanize#167]
Hello. Not sure what's the best way to describe this, other than that inlining scripts is simply not working, not due to the inline code, but the way paths are computed/localized. When I run vulcanize on a large project, the paths computed for scripts are incorrect. They are concatenations of individual script directories. When the inline code runs, it cannot find the files at the incorrect paths.

For example, if I have scripts

&lt;script src='a/b.js'&gt;&lt;/script&gt;

and

&lt;script src='c/d.js'&gt;&lt;/script&gt;

Then sometimes the last will be localized/computed to 'a/c/d.js'

**Comment by garlicnation** [comment]
What version of Vulcanize are you using?

**Comment by benjiec** [comment]
1.0+ does not work. The earlier version, < 1.0, does.

**Comment by garlicnation** [comment]
Vulcanize 1.0+ only works with polymer 0.8 projects, the 0.5 releases are still the way to go for older proejcts.

**Comment by indolering** [comment]
`vulcanize --inline-scripts easy-reg-manager.html ` doesn't inline scripts and it produces a vulcanized.html file.  `vulcanize --inline-scripts easy-reg-manager.html > vulcanized2.html` produces an empty vulcanized file.

**Comment by azakus** [comment]
What is an `easy-reg-manager.html`?

**Comment by indolering** [comment]
@azakus a Polymer web component.

**Comment by 105424** [comment]
Hey,

I'm also having issues with the inline scripts. 
Css files are inlined correctly (as far as i can see) but the scripts tags remain

I run the following command: `vulcanize --inline -s gulp/global.html -o public/global.html` with v0.7.10 (i'm using polymer v0.5.5)

Where gulp/global.html is a file that contains:
`<script type="vendor/webcomponents/webcomponents.js"></script>`
`<link rel="import" href="vendor/polymer/polymer.html">`
`<link rel="import" href="vendor/paper-button/paper-button.html">`
`<script type="../javascripts/sort.js"></script>`

When i look at the ouput the sort and webcomponents script tags are still there (without the code anywhere else in the file).  Curiously though the `<script src="polymer.js"></script>` in polymer.html is inlined correctly

**Comment by azakus** [comment]
Is your source actually using using the `type` attribute instead of `src`? I would fully expect the behavior you see in that case, as `vulcanize` does not process non-javascript script types.

**Comment by indolering** [comment]
@azakus does it require a Javascript type?  I'm pretty sure that I had included the JS type in the tag, I'll report back after I migrate to Polymer 0.9.

@105424 use of "type" is really weird, I think that the default behavior for script tags with src attributes and no type attribute should be to assume that it is JS and inline it.

**Comment by hawkett** [comment]
I ran into some issues a while back with type being specified: https://github.com/webcomponents/webcomponentsjs/issues/273

**Comment by azakus** [comment]
@indolering The supported cases are no type, type='application/javascript', and type='text/javascript'
https://github.com/Polymer/vulcanize/blob/master/lib/matchers.js#L24-L33

**Comment by indolering** [comment]
@benjiec Are you using Polymer .5 or .8/.9?  My issue was with pre-1.0 Vulcanize and the date makes it appear as if @hawkett was using pre-1.0 Vulcanize as well.  If @benjiec was having trouble with pre-1.0 Vulcanize/Polymer 0.5, I say we close this until someone replicates it with a current version.

**Comment by azakus** [comment]
@hawkett Fixed that in webcomponents/webcomponentsjs#312.

@benjiec Can you retry with 1.6.0? This sounds like it might be https://github.com/Polymer/vulcanize/issues/175, which was fixed in 1.4.2

**Comment by benjiec** [comment]
I am using Polymer .5, and pre-1.0 Vulcanize works for me. Post 1.0 vulcanize does not work for me, but as someone pointed out, it's supporting later versions of Polymer.

**Comment by indolering** [comment]
Uhh, I vote to close this.

**Comment by 105424** [comment]
I just realized my typo :(
Fixed it and it's working perfectly. Sorry for the confusion.
