### ISSUE TITLE
Using vulcanize programmatically

### ISSUE THREAD

**Issue by AchrafLansari** [Polymer/vulcanize#168]
I have an issue with require.js 
"Module name "fs" has not been loaded yet for context" 
can we have more documentation about how to use the vulcanize library on the import side ?

Thanks

**Comment by azakus** [comment]
Is this enough information for you: https://github.com/Polymer/vulcanize#using-vulcanize-programmatically?

**Comment by AchrafLansari** [comment]
My problem is that i dont know what the js file that need to import in my index.html so i can use vulcanize progammatically like in the link, 

Thanks

**Comment by azakus** [comment]
Sorry, I can't tell if you still have a question for me. Feel free to reopen if there is still an issue.
