### ISSUE TITLE
Vulcanization breaks PolymerElements/paper-icon-button (#^0.8.0)

### ISSUE THREAD

**Issue by kdex** [Polymer/vulcanize#170]
Referencing [this](https://github.com/PolymerElements/paper-icon-button/issues/2) issue, as I am not sure whether `paper-icon-button` or `vulcanize` needs to be changed to fix it.

**Comment by manifest** [comment]
I had this issue with vulcanize ~v7.1. On v1.3.0 it works fine.

**Comment by azakus** [comment]
Only vulcanize 1.x will work on elements depending on Polymer 0.8+

**Comment by rsORAU** [comment]
I am still having errors result from running vulcanize on a file that imports paper-icon-button.  I have verified that my version of vulcanize is 1.14.8 and my version of paper-icon-button is 1.1.1. Could you please explain what was supposed to have been fixed with the listed resolution?
