### ISSUE TITLE
Href '#' URL fragments do not work with abspath on

### ISSUE THREAD

**Issue by seahrh** [Polymer/vulcanize#173]
Webroot is set as `abspath`. After html is vulcanized, anchors with `href` referencing '#' url fragments do not work. Instead, anchor is pointing to http://localhost/path/to/html/#

**Comment by azakus** [comment]
What version of vulcanize are you using?

**Comment by seahrh** [comment]
I'm using vulcanize 0.7.5 and grunt-vulcanize 0.6.1

**Comment by azakus** [comment]
Ah, that was fixed in 0.7.6 with https://github.com/Polymer/vulcanize/commit/115870286b49f3cedbe15e6ac384a100698f2f16. 0.7.10 is the latest for polymer 0.5 elements.

**Comment by seahrh** [comment]
Yes that fixed the problem, thank you!
