### ISSUE TITLE
Hangs on cyclic dependencies

### ISSUE THREAD

**Issue by mbykovskyy** [Polymer/vulcanize#176]
Cyclic dependencies used to be handled by `0.7.10` and earlier versions, but some time between `0.7.10` and the current version this got broken. I don't really have a good use case for why cyclic dependencies should be allowed but I do think that they should be handled.

**Comment by garlicnation** [comment]
Cyclic dependencies should be working. Can you provide an example where they're failing?

**Comment by mbykovskyy** [comment]
I should mention that I'm talking about calling vulcanize programmatically. I just realised the callback passed to the `process` function never gets invoked and I have a `resolve` in there for my promise that's why it looks like it's stuck forever.

```javascript
vulcanize.setOptions(options);
vulcanize.process(input, function(error, html) {
  console.log("Doesn't get here.");
});
```

The questions I have now is should that callback be invoked all the time? Is `process` function blocking?

**Comment by mbykovskyy** [comment]
Also if it helps, `Ignoring duplicate element definition: undefined` is printed in the console and there's no HTML output.

**Comment by garlicnation** [comment]
You need to keep using vulcanize ^0.7.0 for polymer 0.5 elements. Vulcanize 1.0+ only works with polymer 0.8 elements.

**Comment by mbykovskyy** [comment]
Ok I'll migrate the elements to 0.8 and see if the callback gets called this evening.

**Comment by mbykovskyy** [comment]
I migrated my test to 0.8 elements. The `Ignoring duplicate element definition:` message doesn't show up anymore but the `process` function still doesn't call the callback.

index.html
```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="import" href="existing-component.html">
    <link rel="import" href="cyclic-dependency-component-a.html">
  </head>
  <body>
    <existing-component>Hello Import!</existing-component>
    <cyclic-dependency-component-a></cyclic-dependency-component-a>
  </body>
</html>
```
existing-component.html
```javascript
<link rel="import" type="css" href="style.css">

<dom-module id="existing-component">
  <template>
    <content></content>
  </template>
</dom-module>
<script>
  Polymer({is: 'existing-component'});
</script>
```
cyclic-dependency-component-a.html
```javascript
<link rel="import" href="cyclic-dependency-component-b.html">

<dom-module id="cyclic-dependency-component-a">
  <template>
    <cyclic-dependency-component-b></cyclic-dependency-component-b>
  </template>
</dom-module>
<script>
  Polymer({is: 'cyclic-dependency-component-a'});
</script>
```
cyclic-dependency-component-b.html
```javascript
<link rel="import" href="cyclic-dependency-component-a.html">

<dom-module id="cyclic-dependency-component-b">
  <template>
    <cyclic-dependency-component-a></cyclic-dependency-component-a>
  </template>
</dom-module>
<script>
  Polymer({is: 'cyclic-dependency-component-b'});
</script>
```
