### ISSUE TITLE
[1.4.4] Invalid urls after vulcanize --inline-css

### ISSUE THREAD

**Issue by cedric-marcone** [Polymer/vulcanize#180]
Hey,

The CSS of my components are linked inside their dom-module with a ``<link rel="import" type="css">``.

```html
<dom-module id="my-component">
  <link rel="import" type="css" href="my-component.css">
  <template>
    <div class="outer"></div>
  </template>
</dom-module>
```

If the externalized CSS contains a reference to another asset...

```css
.outer {
  background: url(image.svg);
}
```

...then its path is not rewritten and l end up w/ a 404.

If I embed the the stylesheet inside the dom-module with a ``<style>``tag, it works perfectly, the path is changed in the built file.

**Comment by garlicnation** [comment]
Nice catch! This should be straightforward to fix.
