### ISSUE TITLE
[1.4.4] vulcanize output has incorrect ordering

### ISSUE THREAD

**Issue by hawkett** [Polymer/vulcanize#181]
I've come across an issue that I can resolve in this instance, but looks like it could point to a larger problem.

I have a polymer 9.0 behaviour defined that looks like:

```
<link rel="import" href="../other-behavior/other-behavior.html">

<script>
  DatastoreBehavior = [OtherBehavior, { <behaviour content> }];
</script>
```

With OtherBehavior defined as:

```
<link rel="import" href="../../../bower/iron-meta/iron-meta.html">

<script>
  OtherBehavior = { <behavior content> };
</script>
```

The order in which these files are included in the vulcanize output:

1. DatastoreBehavior
2. IronMeta
3. OtherBehavior

i.e. DatastoreBehavior's reference to OtherBehavior is undefined because OtherBehavior is included after DatastoreBehavior.

The complete set of imports in the file being vulcanized:

```
<link rel="import" href="../../../../bower/test-fixture/test-fixture.html">

<link href="../my-datastore.html" rel="import">
```

and of 'my-datastore.html'

```
<link rel="import" href="../../../bower/polymer/polymer.html">

<link rel="import" href="../../../components/datastore-behavior/datastore-behavior.html">
<link rel="import" href="../../../components/other-behavior/other-behavior.html">
```

*Note*: I don't actually need other-behavior.html here - it just demonstrates the problem - i.e. that the import ordering in 'my-datastore.html' appears to be trumping an actual dependency ordering - namely that datastore-behavior.html declares a dependency on other-behavior.html, but the sibling ordering in my-datastore.html takes precedence. Seems this should be the other way around?

**Comment by azakus** [comment]
I think this is fixed in 1.8.1 which uses hydrolysis 1.12 and an ordering fix: https://github.com/Polymer/hydrolysis/pull/117.

Please reopen if this is not the case.
