### ISSUE TITLE
[1.4.4] 'no resolver found' when running vulcanize

### ISSUE THREAD

**Issue by hawkett** [Polymer/vulcanize#182]
I'm seeing the following output when running :

```
$ vulcanize index.html > build.html
no resolver found
undefined
```

index.html looks like:

```
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>My App</title>
  <meta name="description" content="My App">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">

  <script src="../bower/webcomponentsjs/webcomponents-lite.min.js"></script>

  <link rel="import" href="../javascript-components/my-typekit.html">

  <link rel="import" href="../bower/iron-meta/iron-meta.html">
</head>
<body class="fullbleed">
  <iron-meta key="self" value='{"instanceKey":"1", "parentKey":"null", "processKey":"?", "groupKey":"1"}'></iron-meta>
</body>
</html>
```

Everything looks pretty straight forward - the only import that may be a little odd is the typekit one, and if I remove it then things work fine:

```
<script src="http://use.typekit.net/myTypekitCode.js"></script>
<script>try{Typekit.load();}catch(e){}</script>
```

Are there any obvious issues with doing this?

**Comment by hawkett** [comment]
Also getting this on simpler js imports - e.g. firebase.html -

```<script src="https://cdn.firebase.com/js/client/2.2.4/firebase.js"></script>```

**Comment by azakus** [comment]
Are you using the `--inline-script` flag?

**Comment by hawkett** [comment]
No - just the command shown above.

**Comment by azakus** [comment]
@garlicnation, is hydrolysis always trying to evaluate scripts? I suspect that the fs resolver fails on urls and when it falls back to nothing we give up there.

**Comment by hawkett** [comment]
Seems to occur the same if I do include --inline-scripts

**Comment by garlicnation** [comment]
Yeah. Can we do XHR in pure node? I want to follow external scripts unless it's totally impossible.

**Comment by hawkett** [comment]
A couple of thoughts:

* An interim solution/step could be to not worry about following, but at least place the content of the import (script tags) at the appropriate de-duped location, rather than drop out with 'no resolver found' - at least the source will functionally vulcanize?
* It's likely that people will want to inline external scripts in most cases, but with an occasional exception (e.g. stripe.js always needs to be loaded remotely at runtime). At the moment I'm reading that the only way to achieve this is by putting the import in a separate directory and using --exclude. It would be nice to specify domains to exclude from remote script inlining. Alternative might be to have a separate *--inline-external-scripts* flag and be sure to keep everything else local.

**Comment by azakus** [comment]
@garlicnation the network code in node is very low level, we'd probably have to add another dependency.

Another wrinkle is that `Hydrolysis.Analayzer._processScript` will always throw on an unproccesable script, and that fails the promise chain far before I could handle it in vulcanize.

**Comment by azakus** [comment]
Ok, simple short term fix is to use an NoopResolver for http and https resources, and just handle it specifically in `inlineScripts`.

**Comment by Meligy** [comment]
I think this doesn't work for protocol relative URLs (like "[//example.com/file.js](//example.com/file.js)" instead of "http://example.com/file.js" or "https://example.com/file.js").
