### ISSUE TITLE
inline css for <link rel="stylesheet" href="a.css'> ?

### ISSUE THREAD

**Issue by kyuwoo-choi** [Polymer/vulcanize#184]
hello vulcanize.

I wish vulcanize inlines css with \<link rel="stylesheet" href="a.css"> tag. I know it works with \<link rel="import" type="css"> but I don't understand why vulcanize inlines with rel=import not just rel=stylesheet.

and do you have any suggestion to get it work without modifying vulcan.js?

**Comment by azakus** [comment]
We should just add this functionality back.

**Comment by peterwmwong** [comment]
+1 I'm currently working around this in my build (swapping link attributes for production build). Kinda annoying.
