### ISSUE TITLE
[1.5.1] Strip mode removal leads to a fun issue

### ISSUE THREAD

**Issue by cedric-marcone** [Polymer/vulcanize#185]
Hey !

Porting an app from 0.5 to 0.9, I stumbled on a cute one :)

-> I use vulcanize 1.5.1 as I need it to build a ^0.9.0 project.

The targeted app drags an `<iron-icon>` which drags `<iron-flex-layout>` as a dependency.
The `<iron-flex-layout>` custom-style is injected via vulcanize into an html file.

Everything works fine :
http://output.jsbin.com/vilaju/2/

**BUT**, if I minify the inlined css in the html file, it produces an insane output : http://output.jsbin.com/naxetig/2/

I double checked and the minification step in the gulp build chain is indeed the culprit.

So why bothering you ? :) ...because you removed `--strip` and I'm following your recommendations : I use `html-minifier` which can minify inlined css by invoking `clean-css` : what a mess...

I'd like to cross post this issue to its github repo but, unfortunately, as Polymer uses custom css mixins syntax we're not the common use case... The root of the problem is overlapping braces :
```css
* {
  --my-mixin: {
     prop: value;
  }
}
```

If only you could restore the `--strip` mode it would save us a ton of headaches ;)

Thoughts ?

**Comment by cedric-marcone** [comment]
I circumvented the problem w/ a nasty hack in the gulp build.

If you don't restore `--strip` mode, maybe you could give us hints in the README.md on the recommended way of doing it ?

For the record, the working gulp task (with the nasty replace hack) :

```js
var htmlmin = require('gulp-htmlmin');
var replace = require('gulp-replace');

gulp.task('post-html', ['vulcanize'], function() {
  return gulp.src('build/index.html'))
    .pipe(htmlmin({
      removeComments: true,
      collapseWhitespace: true,
      conservativeCollapse: true,
      collapseBooleanAttributes: true,
      removeAttributeQuotes: true,
      removeEmptyAttributes: true,
      customAttrAssign: [ /\?=/, /\$=/ ]
    }))
    .pipe(replace(/\n\s*/g, ''))
    .pipe(replace(/\/\*.*?\*\//g, ''))
    .pipe(gulp.dest('build'));
 });
```

... And the failing one (minifyCSS is the culprit) :

```js
var htmlmin = require('gulp-htmlmin');

gulp.task('post-html', ['vulcanize'], function() {
  return gulp.src('build/index.html'))
    .pipe(htmlmin({
      removeComments: true,
      collapseWhitespace: true,
      conservativeCollapse: true,
      collapseBooleanAttributes: true,
      removeAttributeQuotes: true,
      removeEmptyAttributes: true,
      customAttrAssign: [ /\?=/, /\$=/ ],
      minifyCSS: true
    }))
    .pipe(gulp.dest('build'));
 });
```

**Comment by azakus** [comment]
The tool `minifyCss` uses is not compatible with our css custom variable usage.

I am working on a "Do the right thing" build tool/gulp task that may include html minifier, but I want vulcanize to stay relatively simple.

**Comment by cedric-marcone** [comment]
Good to hear :) Thanks.

**Comment by azakus** [comment]
All in one tool published as [polybuild](https://www.npmjs.com/package/polybuild).

Still haven't found a good html minifier that doesn't blow up. `html-minifier` seems to hang pretty easily.
I hope to add an AST based minifier at some point.

I'll open an issue there and link to this one.

**Comment by cedric-marcone** [comment]
Great ! Thanks @azakus :)
