### ISSUE TITLE
failure when inline scripts contain es6 template strings

### ISSUE THREAD

**Issue by dstockwell** [Polymer/vulcanize#186]
eg. this file will fail:

    <script>`hello ${'world'}`</script>

With `Error: Line 1: Unexpected token ILLEGAL`

**Comment by azakus** [comment]
@garlicnation Sounds like a hydrolysis feature request to support ES6 :)

**Comment by azakus** [comment]
I'll leave this open until https://github.com/Polymer/hydrolysis/pull/105 is landed.
