### ISSUE TITLE
abspath isn't working properly

### ISSUE THREAD

**Issue by Nyle** [Polymer/vulcanize#188]
Even when using the -p option vulcanize still is looking for references beginning with "/" at the root of my fs. To make sure it wasn't related to the project I'm working on, I made a directory "test" with the following files:

test.html
```
<!DOCTYPE html>
<html>
  <head>
    <link rel="import" href="/a.html">
  </head>
  <body>
  </body>
</html>
````
a.html
```
<polymer-element name="a">
  <template>
  </template>
</polymer-element>
````

While in the same directory as the test directory is located `vulcanize -p"test/" /test.html` gives me
```
/usr/local/lib/node_modules/vulcanize/node_modules/hydrolysis/lib/loader/fs-resolver.js:21
      throw err;
            ^
Error: ENOENT, open 'test.html'
    at Error (native)
```
`vulcanize -p"test/" test/test.html` gives
```
/usr/local/lib/node_modules/vulcanize/node_modules/hydrolysis/lib/loader/fs-resolver.js:21
      throw err;
            ^
Error: ENOENT, open '/a.html'
    at Error (native)
```
I have also tried giving an absolute path to the test directory, running vulcanize from within the test directory and using `--abspath` instead of `-p`. If I create an empty file `/a.html`, `vulcanize -p"test/" test/test.html` runs just fine, printing
```
<!DOCTYPE html><html><head><meta charset="UTF-8">
    </head>
  <body>
  

</body></html>
```

I'm using version 1.6.0 of vulcanize, installed via npm using `sudo npm install -g vulcanize` and am running all of this on OSX 10.10.3.

**Comment by aleclofabbro** [comment]
I'm experiencing the same issue with vulcanize 1.8.1 on Ubuntu 14.04

**Comment by aleclofabbro** [comment]
found the undocumented solution:
`vulcanize --abspath=test/ test.html`
