### ISSUE TITLE
vulcan.js Undefined is not a function

### ISSUE THREAD

**Issue by CAH-MikeEarley** [Polymer/vulcanize#189]
I'm adding polymer to an ember project using these instructions: 
http://www.programwitherik.com/how-to-add-polymer-to-your-ember-project/
When I'm attempting to run `ember serve`, I'm getting an error on vulcan.js, like so: 

<pre>
/fuse/source/drug-client/node_modules/broccoli-vulcanize/node_modules/vulcanize/lib/vulcan.js:167
    excludes.forEach(function(r) {
             ^
TypeError: undefined is not a function
    at buildLoader (/fuse/source/drug-client/node_modules/broccoli-vulcanize/node_modules/vulcanize/lib/vulcan.js:167:14)
    at Object.setOptions (/fuse/source/drug-client/node_modules/broccoli-vulcanize/node_modules/vulcanize/lib/vulcan.js:182:22)
    at /fuse/source/drug-client/node_modules/broccoli-vulcanize/index.js:36:17
    at /fuse/source/drug-client/node_modules/broccoli-vulcanize/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:95:15)
</pre>

**Comment by azakus** [comment]
The instructions in that post are for an older version of vulcanize, and presumably broccoli-vulcanize as well.

Are you using Polymer 0.5 or Polymer 0.8?

**Comment by CAH-MikeEarley** [comment]
Contents of bower.json: 

<pre>
{
  "name": "polymer",
  "version": "0.9.2",
  "main": [
    "polymer.html"
  ],
  "license": "http://polymer.github.io/LICENSE.txt",
  "ignore": [
    "/.*",
    "/test/"
  ],
  "authors": [
    "The Polymer Authors (http://polymer.github.io/AUTHORS.txt)"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/Polymer/polymer.git"
  },
  "dependencies": {
    "webcomponentsjs": "^0.7.1"
  },
  "devDependencies": {
    "web-component-tester": "*"
  },
  "private": true
}
</pre>

**Comment by maca** [comment]
I am having the same error when setting stripExcludes: true when building with gulp

    { [TypeError: undefined is not a function]
      name: 'TypeError',
      message: 'undefined is not a function',
      stack: 'TypeError: undefined is not a function\n  at Object.<anonymous> (/home/maca/Web/project/ot-chat/node_modules/gulp-vulcanize/node_modules/vulcanize/lib/vulcan.js:288:30)\n  at Array.forEach (native)\n  at Object.<anonymous> (/home/maca/Web/project/ot-chat/node_modules/gulp-vulcanize/node_modules/vulcanize/lib/vulcan.js:287:26)\n',
      fileName: '/home/maca/Web/project/ot-chat/.build/components/ot-chat.html',
      showStack: false,
      showProperties: true,
      plugin: 'gulp-vulcanize' }}

The only way I could make it work is by passing an array as stripExcludes with the absolute path of the files I wanted excluded instead of `true`

    gulp.task 'vulcanize', ['build', 'copy-deps'], ->
      gulp.src "#{opts.buildDir}/components/#{opts.index}"
        .pipe vulcanize(
          abspath: '/'
          excludes: []
          stripExcludes: ["#{__dirname}/.build/polymer/polymer.html"]
        ).on('error', log)
        .pipe gulp.dest './'

The other inconvenient I find is that in order to ignore a file, the file must be present, since I am preprocessing my components html and building to a directory that forces me to copy the html dependencies. I wish I didn't have to copy the dependency in order to strip the import. makes sense?

**Comment by azakus** [comment]
Oh shoot, the vulcanize docs are wrong. `stripExcludes` should be an array, not a boolean.

**Comment by azakus** [comment]
Next release `1.10.1` will properly typecheck inputs from the gulp plugin, sorry for the wrong docs!
