### ISSUE TITLE
multiple inlines of polymer

### ISSUE THREAD

**Issue by clux** [Polymer/vulcanize#193]
Hi,

I am trying to combine a couple of polymer 1.0 components into a single file. These vulcanize nicely separately to inline their scripts and css, but they are separate projects, and because they reference their separate bower_components/polymer/polymer.html (albeit at the same version) they get inlined multiple times when trying to vulcanize anything using both of them.

Is there a good way of doing this? Is vulcanize supposed to do handle this?
Is it perhaps preferable to do something like removing the polymer import line from each component instead, and have it prepended to the main bundle instead?

**Comment by clux** [comment]
[I have come to a solution, though it feels a bit hacky](https://github.com/clux/icebreaker/blob/71f79869c3a517ebedb7b4d9585e078e3ec78486/build.sh).

Essentially, each component first vulcanizes in its own dependencies (i.e. not its bower deps), then modifies the relative path to bower dependencies, so that it can be used in a bower setting. Feels a little insane, but I can see all the google web components reference `../polymer/polymer.html` as if each project sits inside a huge `bower_dependencies` folder.

Any comments on if this is intended, or if there's some bower/vulcanize magic I'm missing, would be greatly appreciated.

**Comment by garlicnation** [comment]
The nature of how bower installs dependencies makes it challenging to work with. I encourage you to check out the guide at https://www.polymer-project.org/1.0/docs/start/reusableelements.html. The trick is to treat each of the components in your project as though all of their dependencies are siblings, and only refer to bower_components directly in your final app or site.
