### ISSUE TITLE
"Polymerized stylesheets" are not wrapped in <style> tags when inlined

### ISSUE THREAD

**Issue by Tyriar** [Polymer/vulcanize#194]
From the root README:

> The command
> `vulcanize --inline-css target.html`
> will inline Polymerized stylesheets, `<link rel="import" type="css">`

This is no longer working with or without `--inline-css`, this means that any consumers depending on the official [paper-slider](https://github.com/PolymerElements/paper-slider) or [paper-radio-button](https://github.com/PolymerElements/paper-radio-button) (and more) cannot use vulcanize without explicit exclude rules in a `--config` file.

I'm using: vulcanize@1.8.1, paper-slider@1.0.1, paper-radio-button@1.0.1

Command exhibiting the problem: `vulcanize index.html --inline`

---

Is there some performance benefit to using HTML imports for CSS as opposed to a regular `<link rel="stylesheet">` tag for styles?

**Comment by azakus** [comment]
There is no config file argument for vulcanize 1.x, nor is there a `--inline` flag.
Are you sure you're using vulcanize 1.8?

**Comment by Tyriar** [comment]
I might be having some issues with my node installation then, I'll double check on the weekend and reopen if not. Thanks!
