### ISSUE TITLE
Weird behavior related to import of `webcomponents.js`

### ISSUE THREAD

**Issue by abourget** [Polymer/vulcanize#200]
Running `vulcanize` on:

```
<html><head>
  <link rel="import" href="components/webcomponentsjs/webcomponents.min.js">
  <link rel="import" href="components/polymer/polymer.html">
</head><body></body></html>
```

produces:

```
{ [Error: ENOENT, open 'components/webcomponentsjs/components/polymer/polymer.html']
  errno: -2,
  code: 'ENOENT',
  path: 'components/webcomponentsjs/components/polymer/polymer.html' }
...
```

and (.min taken out):
```
<html><head>
  <link rel="import" href="components/webcomponentsjs/webcomponents.js">
  <link rel="import" href="components/polymer/polymer.html">
</head><body></body></html>
```

```
{ [Error: ENOENT, open 'components/webcomponentsjs/%27%20+%20%27components/polymer/polymer.html']
  errno: -2,
  code: 'ENOENT',
  path: 'components/webcomponentsjs/%27%20+%20%27components/polymer/polymer.html' }
```

Also, when I try with `webcomponents-lite.min.js`, the content of webcomponents is inserted at some place inside the `body` tag.. and when `polymer-micro.html` runs:

```
(function() {
function resolve() {
document.body.removeAttribute("unresolved");
}
if (window.WebComponents) {
addEventListener("WebComponentsReady", resolve);
} else {
resolve();
}
})();
```

it does so before the `body` tag, and crashes with: `Uncaught TypeError: Cannot read property 'removeAttribute' of null`.. because `document.body` isn't there yet... cause it's calling `resolve()` right away.

w00t.. that's quite a blocker for us right now.

**Comment by abourget** [comment]
I'm using mostly Chrome, so I worked around my particular case by sticking:

```
  <script>
  window.WebComponents = true;
  </script>
```

before loading `polymer.html`.. but I think it's quite nasty.

**Comment by m4b** [comment]
Your first import should be a script tag:

````html
  <script src="components/webcomponentsjs/webcomponents.min.js"></script>
````

Lastly, ENOENT means the file isn't found.  If the above doesn't solve your problem, check if you've got a `bower_components` folder instead of `components`, if you're using bower and haven't renamed the components folder.

**Comment by abourget** [comment]
wow, I'm so very sorry for this report.. I should have put a `script` tag indeed.
