### ISSUE TITLE
Assetpath attribute in dom-module has incorrect paths after vulcanize

### ISSUE THREAD

**Issue by devAtPolydeals** [Polymer/vulcanize#205]
After Vulcanize, it adds the attribute 'assetpath' to <dom-module>. For me those values are all incorrect. Some have 
```<dom-module id="iron-pages" assetpath="../wer_components/iron-pages/">```
others are
```<dom-module id="iron-a11y-announcer" assetpath="../ower_components/iron-a11y-announcer/">```

they all have to be bower_components and with path's that are dependant on the project.

**Comment by azakus** [comment]
Are you using Windows? This may be related to #202

**Comment by devAtPolydeals** [comment]
Yes I am. Ya looks like it is related. Also, it has varied implications, my styling gets all messed up etc.
