### ISSUE TITLE
Drop reference to html-minifier, or at least include a note.

### ISSUE THREAD

**Issue by jcgregorio** [Polymer/vulcanize#206]
Right now html-minifier doesn't work with Polymer 1.0 code, in particular attributes that include $:

  https://github.com/kangax/html-minifier/issues/377

The link to html-minifier here:

  https://github.com/Polymer/vulcanize#what-happened-to-feature-from-0x

should contain a note about the limitation and a link to the bug until the issue is resolved to save people from losing time on this issue like I did.

**Comment by ecoutu** [comment]
I spent a few hours on this myself, you need to utilize the customAttrAssign option to let html-minifier know about =$ assignments. I was absolutely unable to get it to work from the command line, but I'm using a gulp build process, so it was a breeze to do it programatically:

```
var html = fs.readFileSync('public/index.built.html').toString();
var minifiedHtml = minify(html, {
    customAttrAssign: [/\$=/],
    removeComments: true,
    collapseWhitespace: true
});

fs.writeFileSync('public/index.min.html', minifiedHtml);
```

I gave up trying to get it to minimize the css, I don't think it's possible if you are using css variables and mixins.
