### ISSUE TITLE
does not render properly in Firefox, IE

### ISSUE THREAD

**Issue by azakus** [Polymer/vulcanize#209]
_From @seahrh on June 15, 2015 12:29_

The example code in the docs does not render properly in FF38 and IE11.

    <paper-drawer-panel>
      <paper-header-panel drawer>
        <paper-toolbar>
          <div>Application</div>
        </paper-toolbar>
        <div> Drawer content... </div>
      </paper-header-panel>
      <paper-header-panel main>
        <paper-toolbar>
          <paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
          <div>Title</div>
        </paper-toolbar>
        <div> Main content... </div>
      </paper-header-panel>
    </paper-drawer-panel>

In FF, drawer seems to be truncated. `paper-drawer-toggle` doesn't work.

![paper-drawer-panel-ff](https://cloud.githubusercontent.com/assets/4428622/8159766/8c9f8882-139c-11e5-86b9-29ec4fe03e9a.JPG)

IE's worse:

![paper-drawer-panel-ie](https://cloud.githubusercontent.com/assets/4428622/8159777/990e1430-139c-11e5-8eef-5cacd2429481.JPG)

Changing to the full `webcomponents.min.js` polyfill didn't help.

_Copied from original issue: PolymerElements/paper-drawer-panel#66_

**Comment by azakus** [comment]
_From @blasten on June 17, 2015 0:24_

@seahrh I couldn't replicate the issue. 

If you take that markup along with the imports: 
```html
<link rel="import" href="../../paper-header-panel/paper-header-panel.html">
<link rel="import" href="../../paper-toolbar/paper-toolbar.html">
```
 and you put it in `demo/demo.html`, you should see it working. If you still have issues, can you provide a link that replicates the issue?

**Comment by azakus** [comment]
_From @seahrh on June 17, 2015 4:21_

OK I took the example code and put it in [demo.html](https://gist.github.com/seahrh/8effb305bde5247d4a4c), it works.

However, after vulcanizing the same file, I get the errors shown in the OP.

My vulcanize task:

    gulp.task('vulcanize', function() {

        var DEST_DIR, VULCANIZED_EXT; 
        DEST_DIR = bases.dist + 'WEB-INF/pages';
        VULCANIZED_EXT = '.vul.html';

        return gulp.src(['*.html', '!*' + VULCANIZED_EXT], {
            cwd : DEST_DIR
        }).pipe($.vulcanize({
            inlineScripts : false,
            inlineCss : false,
            stripComments : true
        })).on('error', error).pipe($.rename({
            extname : VULCANIZED_EXT
        })).pipe(gulp.dest(DEST_DIR));

    });

Inline scripts or not, I see the same errors.

On gulp-vulcanize@6.0.1, vulcanize@1.9.1

My work can't be deployed to production if `paper-drawer-panel` only works *un-vulcanized*.

**Comment by azakus** [comment]
@seahrh Are you on Windows? There's probably a path bug in vulcanize on Windows right now: https://github.com/Polymer/vulcanize/issues/202

**Comment by azakus** [comment]
_From @seahrh on June 18, 2015 9:6_

Yes I'm using Win7. Let me try out the fix for Polymer/vulcanize#202 and report back.

**Comment by azakus** [comment]
_From @seahrh on June 18, 2015 10:52_

Updated to vulcanize 1.9.3 and **not** using abspath. Same problem persists.
I'm using other PolymerElements such as `paper-fab` and `paper-input` and they show up fine on the vulcanized page.

**Comment by azakus** [comment]
_From @blasten on June 18, 2015 20:14_

ping @azakus

**Comment by michaelpg** [comment]
I'm seeing the exact same issue.

Adding `--inline-css` to the `vulcanize` command fixes the layout.

In the "Style Editor" in FF, the version generated by `--inline-css` has two extra inline stylesheets (the first two listed, actually) which clearly seems to be the source of the problem:
http://pastebin.com/cVX2n1Cp
http://pastebin.com/aNRxmKs4

Also in the Style Editor, manually importing paper-header-panel.css fixes the layout in the broken vulcanized file.

**Comment by seahrh** [comment]
@michaelpg, thanks for the `inline-css` tip. Yes the vulcanzied page now renders properly in FF39, but the same problem still persists in IE11.

**Comment by JustinCase1089** [comment]
Any news on this issue? ... I have boiled my problem down to precisely this issue in IE11

**Comment by azakus** [comment]
This is actually a Polymer / Template element polyfill bug, where templates are processed before they are upgraded by the polyfill. I've made a PR in Polymer to work around this: https://github.com/Polymer/polymer/pull/2201

**Comment by JustinCase1089** [comment]
thanks
