### ISSUE TITLE
inlineCss not working on Polymer 1.0 project

### ISSUE THREAD

**Issue by Chariyski** [Polymer/vulcanize#212]
Hi guys,

When I try to use:
```
$ vulcanize --inline-css elements.html
```
the following error is presented:
```
{ [Error: ENOENT, open 'c:\test\app\ower_components\paper-item\paper-item-shared.css']
  errno: -4058,
  code: 'ENOENT',
  path: 'c:\\test\\app\\ower_components\\paper-item\\paper-item-shared.css' }
Error: ENOENT, open 'c:\test\app\ower_components\paper-item\paper-item-shared.css'
    at Error (native)
```
Notice that it tries to access 'c:\test\app\ower_components' folder instead of 'c:\test\app\bower_components'. Somehow it looses 'b' in the folder name.

Any ideas ?

**Comment by tuespetre** [comment]
I'm able to inline css without issue. Are you sure there's not a typo somewhere? What's your source?

**Comment by Chariyski** [comment]
I think that there is no typо, because when I remove the --inline-css it is working perfectly fine.
I will be able able to give you the source later today, but the same problem can be seen here : 
http://stackoverflow.com/questions/30819435/vulcanize-inlinecss-not-working-on-polymer-1-0-project/30966457#30966457

**Comment by Chariyski** [comment]
My project is located in C:\test, with the following folder structure:
```
test
-- app
-- -- html
-- -- -- elements.html
-- -- styles
-- -- scripts
-- -- ....
-- bower_components
-- ....
```

And the elements.html contains: 
```
<link rel="import" href="../../bower_components/polymer/polymer.html">

<!-- Iron elements -->
<link rel="import" href="../../bower_components/iron-icons/iron-icons.html">
<link rel="import" href="../../bower_components/iron-icon/iron-icon.html">

<!-- Paper elements -->
<link rel="import" href="../../bower_components/paper-ripple/paper-ripple.html">
<link rel="import" href="../../bower_components/paper-toolbar/paper-toolbar.html">
<link rel="import" href="../../bower_components/paper-item/paper-item.html">
<link rel="import" href="../../bower_components/paper-checkbox/paper-checkbox.html">
<link rel="import" href="../../bower_components/paper-input/paper-input.html">
<link rel="import" href="../../bower_components/paper-button/paper-button.html">
<link rel="import" href="../../bower_components/paper-spinner/paper-spinner.html">
```

**Comment by Chariyski** [comment]
Solution:  http://stackoverflow.com/questions/30819435/vulcanize-inlinecss-not-working-on-polymer-1-0-project/30966457#31098879

**Comment by azakus** [comment]
That's a nice workaround, but it should really just be fixed in vulcanize.

**Comment by angeldevz** [comment]
`inlineCss` is also not working when compiling on `gulp-vulcanize`
```HTML
//CSS file
<link rel="stylesheet" href="style.css">
```
but it is working when using vulcanize directly
```shell
vulcanize --inline-css build/splash.html > build/splash2.html
```

**Comment by eterna2** [comment]
use the same technique.

cuz the standard deck calls paper-styles, which in turn calls roboto.html which in turn calls the google font.

**Comment by angeldevz** [comment]
I am not using any paper element. Im, just importing 
```
<link rel="import" href="../../bower_components/polymer/polymer.html">
```
and I created my own polymer element. 
but it doesn't vulcanize the CSS file I am adding on the main html

```
<link rel="stylesheet" href="style.css">
```
