### ISSUE TITLE
Gulp vulcanize 

### ISSUE THREAD

**Issue by rgbkrk** [Polymer/vulcanize#215]
As reported in https://github.com/sindresorhus/gulp-vulcanize/issues/32, `gulp-vulcanize` is generating:

```
<html><head><meta charset="UTF-8"></head><body></body></html>
```

Even though command line `vulcanize` is working just fine. Perhaps there were API changes that make it incompatible?

**Comment by azakus** [comment]
That's not a lot to go on for me. What does your gulpfile look like; what does the input file to vulcanize look like? Is that file written to disk before you put it into the gulp pipeline?

**Comment by rgbkrk** [comment]
Here's the gulp pipeline:

```
gulp.task('vulcanize', function () {
  gulp.src('dist/jupyter-display-area.local.html')
    .pipe(vulcanize({dest: 'dist', inline: true}))
    .pipe(rename('jupyter-display-area.html'))
    .pipe(gulp.dest('dist'));
});
```

In the above, `dist/jupyter-display-area.local.html` has a simple template and script.

**Comment by azakus** [comment]
What version of gulp-vulcanize are you using? Those arguments are not compatible with the latest version. Are you using Polymer 0.5 or 1.0?

**Comment by rgbkrk** [comment]
I'm not using Polymer at all, just pure web components.

```
"gulp-vulcanize": "^6.0.1"
```

**Comment by azakus** [comment]
I can't reproduce this with an simple gulp task. Do you have another task that replaces the content of `dist/jupyter-display-area.local.html` just before the call to vulcanize?

You may have to use `run-sequence` to order the tasks so that the writes don't conflict.

**Comment by rgbkrk** [comment]
I ended up switching to an all `npm` approach (`npm run build:js`, etc.) and ditching gulp completely. There was a task that was creating `dist/jupyter-display-area.local.html` by just copying the original source.

**Comment by azakus** [comment]
Ah, ok, that was probably the culprit. Gulp 3.x tasks all run concurrently when in a dependency array, and file writes can be batched in bad ways.

Fortunately Gulp 4.x will run serially by default.
