### ISSUE TITLE
Bundling common elements into a separate bundle

### ISSUE THREAD

**Issue by antonmoiseev** [Polymer/vulcanize#218]
Can vulcanize handle bundling of common elements? For example, to give vulcanize two "entry-point" elements as the input and get three bundles as the output: a bundle per entry-point + a bundle with common elements? Manually managing bundles with `--exclude` is tedious and error prone for any decent size project. If it's not implemented, is there a discussion on the topic, an issue to track or a design doc?

**Comment by clintwood** [comment]
+1 this would be nice!

**Comment by azakus** [comment]
This has come up a few times as a major desire of vulcanize.
I'm going to try and make it easy to make a "common" bundle for N entrypoints, with a config format for more advanced use cases like a deeper hierarchy of bundles.

**Comment by clintwood** [comment]
That sounds awesome, thank you!

**Comment by ronnyroeller** [comment]
@azakus I just stumbled over this ticket. Is support for bundles still on the agenda for `vulcanize`? What's the best practice solution right now to generate multiple bundles?

**Comment by garlicnation** [comment]
@ronnyroeller There's the experimental https://github.com/PolymerLabs/web-component-shards, which should work for many cases. I'm very happy to offer any guidance necessary to get started using it.

**Comment by garlicnation** [comment]
Any requests on this feature should be moved to web-component-shards.
