### ISSUE TITLE
Unable to get property '_ctor' of undefined or null reference

### ISSUE THREAD

**Issue by kungufli** [Polymer/vulcanize#223]
After vulcanization I receive this error in IE 11:

`Unable to get property '_ctor' of undefined or null reference`

at this point of the polymer script:
```
Polymer.Templatizer = {
properties: { __hideTemplateChildren__: { observer: '_showHideChildren' } },
_instanceProps: Polymer.nob,
_parentPropPrefix: '_parent_',
templatize: function (template) {
if (!template._content) {
template._content = template.content;
}
if (template._content._ctor) {
```
This error only appear in IE (Chrome, Firefox and Safari works normally) and the page fails to load. Also, the source page (before vulcanization) works normally in IE.

**Comment by azakus** [comment]
Is the webcomponents.js script the first script or import in your page? If not, I suspect the template element polyfill is not getting initialized before your element in IE, which is the last browser to lack template element support.

**Comment by kungufli** [comment]
@azakus you are right, the webcomponents polyfill is imported at the end of the page because of `crisper` (I used this command: `vulcanize --inline-scripts --inline-css index_source.html | crisper --html index.html --js index.js`). However, also if I skip `crisper` (`vulcanize --inline-scripts --inline-css index_source.html > index.html`) I still get the `Unable to get property '_ctor' of undefined or null reference` error and also a new one `Unable to get property 'nodeType' of undefined or null reference` that seem also related to `template` support:
```
<script>Polymer.nar = [];
Polymer.Annotations = {
parseAnnotations: function (template) {
var list = [];
var content = template._content || template.content;
this._parseNodeAnnotations(content, list);
return list;
},
_parseNodeAnnotations: function (node, list) {
return node.nodeType === Node.TEXT_NODE ? this._parseTextNodeAnnotation(node, list) : this._parseElementAnnotations(node, list);
},
```
Any hint about that?

**Comment by azakus** [comment]
My comment was really asking about where `webcomponents.js` is in your source file `index.html`. It should be the first script, preferably in `<head>`.

**Comment by kungufli** [comment]
Absolutely yes, this is the initial portion of my source `index.html`file:
```
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="images/icon.png">
    <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
```

**Comment by azakus** [comment]
Thanks. I wonder if this might be related to webcomponents/webcomponentsjs#362.
I'm not sure why using vulcanize would matter, except if some part of the HTMLImports polyfill flow is making up for this deficiency.

**Comment by alefwmm** [comment]
Is there any workaround for this problem?

**Comment by kgastelum** [comment]
had same issue, replaced webcomponents-lite with webcomponents.js and problem went away.

**Comment by kungufli** [comment]
Thank You @kgastelum, I confirm that the problem is not present if I use `webcomponents.js` (or `webcomponents.min.js`), so it seems there is something wrong in the `lite` version of `webcomponents` on IE, probably the issue reported by @azakus.

**Comment by kungufli** [comment]
Any news on that? Since I reported this problem there have been several updates to `polymer`, `vulcanize` and `webcomponentsjs` but I still get the `Unable to get property '_ctor' of undefined or null reference` error in IE and Edge browsers on vulcanized pages that uses `webcomponents-lite`. The same pages works normally before vulcanization, or if I use the non-lite version of `webcomponents`.

**Comment by sandro-k** [comment]
+1

**Comment by rubenstolk** [comment]
+1000

**Comment by azakus** [comment]
@garlicnation and I have been looking at this, looks like the culprit is Polymer forcing CustomElements to upgrade in the document before the Template polyfill has run.

**Comment by azakus** [comment]
Should be Fixed by Polymer/polymer#2707

**Comment by rubenstolk** [comment]
I'll have a look today and confirm!

**Comment by azakus** [comment]
Actually should be fixed by webcomponents/webcomponentsjs#439. I'll make a release tomorrow with that in.

**Comment by rubenstolk** [comment]
Fantastic, will hold my horses!

**Comment by rubenstolk** [comment]
@azakus can you indicate when there will be a new version of webcomponents with this fix?

**Comment by azakus** [comment]
@rubenstolk Yes, in a few minutes. There was some concern that the PR didn't address all the possible scenarios that would fail, but those have been put to rest now.

**Comment by azakus** [comment]
Webcomponents 0.7.17 should be out now with that fix.

**Comment by rubenstolk** [comment]
Thanks so much @azakus!

**Comment by garlicnation** [comment]
@rubenstolk Can you confirm that the issue is resolved for you with the latest wcjs?

**Comment by rubenstolk** [comment]
Will do that in couple of hours

**Comment by rubenstolk** [comment]
Yep, verified, it does solve the issue and my app runs fine in IE again now!

**Comment by kungufli** [comment]
It's working for me too. Thanks you all. I'm closing the issue.
