### ISSUE TITLE
HTML comment in vulcanized file was always stripped regardless of `--strip-comments` option

### ISSUE THREAD

**Issue by onelaview** [Polymer/vulcanize#224]
With `vulcanize` version `1.10.2`, I tried to vulcanize following **index.html**
(note the `<!-- Hello -->` comment)

```html
<!DOCTYPE html>
<html>
<head>
    <!-- Hello -->
    <link rel="import" href="elements/my-element1.html">
</head>
<body>

</body>
</html>
```

And my **my-element1.html** is as follows
(note the `<!-- My Element1 -->` comment)

```html
<link rel="import" href="../bower_components/polymer/polymer.html">
<!-- My Element1 -->
<dom-module id="my-element1">
    <script>
        Polymer({
            is: 'my-element1',
            ready: function () {
                console.log('my-element1 is ready');
            }
        });
    </script>
</dom-module>
```

After being vulcanized, regardless of `--strip-comments` option, my vulcanized file doesn't contain my original comments in the html files.

PS. I pushed sample source code [here](https://github.com/onelaview/test-vulcanize-2). Just run `bower install` before `vulcanize` with or without `--strip-comments` to see the result.

**Comment by azakus** [comment]
Oh yep, that's pretty dumb.

**Comment by azakus** [comment]
Ah this is a regression from moving to a class based layout.
