### ISSUE TITLE
Generating single external CSS file

### ISSUE THREAD

**Issue by Meligy** [Polymer/vulcanize#225]
We have inline CSS option, which will take CSS from external files and inline them into HTML.

Is there a way to take all the (otherwise inline) CSS into a single external CSS file?

Note: I think Crisper (the recommended tool for CSP scenarios) would do that for JavaScript, but not CSS.

**Comment by azakus** [comment]
You probably don't want a single CSS file.
Polymer uses CSS scoping techniques like ShadowDOM and Custom CSS Properties, which rely on DOM position to scope your styles in your components.

Making a single CSS file would break that.
