### ISSUE TITLE
Confused about multiple bundles and what to include and what not

### ISSUE THREAD

**Issue by nojaf** [Polymer/vulcanize#233]
Hi,

I've create a single vulcanized html file with all my components in it. However the file was quite large and contained my preloader element so I want to split things up.

So I have index.html:
```html
	<script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
	<link rel="import" href="bower_components/polymer/polymer.html" />
	<link rel="import" href="components/loading.html">
	<link rel="import" href="components/a.html">	
	<link rel="import" href="components/b.html">	
	<link rel="import" href="components/c.html">	
	<link rel="import" href="components/d.html">	
	<link rel="import" href="components/e.html">
```

So I want to create a bundled file for my loader and one for all the other things.
loading.html uses ```polymer, iron-flexbox and paper-spinner```.
Since everything uses polymer I think I should exclude it and keep the link in my index.html.
So neither of my bundles contains it and it can't be executed twice. **Am I correct here?**

Can the second bundle safely ignore ```iron-flexbox and paper-spinner``` as well since those elements are already part of the first bundle?

So following this reasoning, I would end up with:
```html
	<script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
	<link rel="import" href="bower_components/polymer/polymer.html" />
	<link rel="import" href="loading.vulcanized.html">
	<link rel="import" href="components.vulcanized.html">	
```

How will the browser know that it can only parse ```components.vulcanized.html``` once ```loading.vulcanized.html``` is processed? And that ```loading.vulcanized,html``` can only be processed once ```polymer.html``` is processed?

Thanks,

nojaf

**Comment by azakus** [comment]
HTML Imports will deduplicate dependencies as long as the URLs lead to the same file. Since vulcanize removes those links, you will have to make sure that both bundles do not inline duplicated dependencies.

We have a new tool [web-component-shards](https://github.com/PolymerLabs/web-component-shards) that makes bundles, and probably matches your usecase.

@garlicnation
