### ISSUE TITLE
Vulcanized pages doesn't work in Firefox, Safari and IE

### ISSUE THREAD

**Issue by kungufli** [Polymer/vulcanize#235]
Pages vulcanized with version 1.10.3 doesn't work in Firefox, Safari and IE, but only in Chrome.  Firefox report this error: `TypeError: this.$ is undefined` and similar errors appears in Safari and IE.

**Comment by addyosmani** [comment]
Potentially related: https://github.com/Polymer/vulcanize/issues/234

**Comment by azakus** [comment]
If your app works with Polymer 1.0.9 when vulcanizing, then it is #234

**Comment by kungufli** [comment]
I confirm that the app works with Polymer 1.0.9, at least on Firefox and Safari (on IE I still have the `Unable to get property '_ctor' of undefined or null reference` problem reported here https://github.com/Polymer/vulcanize/issues/223, but this is another story).

**Comment by azakus** [comment]
Thanks, that confirms for me that #234 is the actual culprit.
