### ISSUE TITLE
Vulcanized result displays scripts instead of HTML

### ISSUE THREAD

**Issue by caraya** [Polymer/vulcanize#237]
I'm working with the Polymer Starter Kit (latest version downloaded on Monday) and I'm getting the error below when I run vulcanize on an app that has the firebase-collection element. 

I haven't been able to debug the issue. 

![Resut of vulcanized build display](https://cloud.githubusercontent.com/assets/409841/9694556/8b0d05e2-530e-11e5-987a-3b954e4c9565.png)

**Comment by caraya** [comment]
Problem was solved with PSK 1.1

**Comment by caraya** [comment]
When I see the results of deploying a vulcanized version of my project I see the same result. It worked for a little while so I'm starting to think the problem is with one of my elements. but it works when I serve the project locally.

The site is at http://caraya.github.io/project-list/

the code is at https://github.com/caraya/project-list/

**Comment by hawkett** [comment]
I have previously seen this issue as well - would be good to know what the fix was - a change in vulcanize or a change in the app?

**Comment by caraya** [comment]
I thought I had solved it but it appeared again.  The project builds successfully but it appears to add scripts to the body of the page. I suspect is one of my components but can't really tell as the code passes jshint and vulcanize checks and it builds correctly

The code is in a branch: https://github.com/caraya/project-list/tree/vulcanize-issue
(just realized I had deleted the code from master, will restore it when I get home)

the site is at: http://caraya.github.io/project-list/

**Comment by hawkett** [comment]
IIRC the problem for me was trying to vulcanize index.html - if I vulcanized only elements.html and left index.html alone, this problem went away. Your mileage may vary.

**Comment by azakus** [comment]
@caraya Can you give me a bit of guidance on where to start looking in your codebase? There's a lot of stuff there.

**Comment by caraya** [comment]
@azakus it's all under the app directory... you can ignore everything else.

**Comment by caraya** [comment]
@azakus  The code is under polymer-starter-kit/ and the elements are under polymer-starter-kit-master/app

**Comment by jyang** [comment]
I am seeing this issue with index.html using PSK 1.1.1.

**Comment by abendigo** [comment]
I am getting the same error. I am not using PSK, just some code I wrote myself. When I add firebase-collection, gulp-vulcanize starts to generate broken code. I'll try to build a simple example, and add it here.

**Comment by garlicnation** [comment]
Without more information I'm going to close this as a PSK, not vlucanize, bug.
