### ISSUE TITLE
Characters with accents are not properly converted/formated

### ISSUE THREAD

**Issue by absolutkurant** [Polymer/vulcanize#239]
I can't reopen the issue, but I'm having the same problem as in #67 , hence the same title.
The files to vulcanize are saved as UTF-8. Just to add an example, something like 'Economía' is outputted as 'Econom├¡a'
Since the old issue was closed the code was changed considerably, I gave it a quick look but couldn't exactly pinpoint where the problem is.

**Comment by azakus** [comment]
Vulcanize forces output files to use UTF-8 encoding since 1.0. Can you check what version you are using with `vulcanize --version` ?

**Comment by absolutkurant** [comment]
Sorry, I forgot I had opened this issue. I was working on windows at the time and using Powershell, which by default outputs UTF-16. It took me longer than I'd like to admit to realize this was the problem, but simply switching to another CLI solved everything. Thanks for taking a look nonetheless.

**Comment by azakus** [comment]
Thanks for the note about Powershell. That is very disturbing to think that the shell may muck with output files :-1:
