### ISSUE TITLE
webserver root -p error when --inline-scripts or --inline-css

### ISSUE THREAD

**Issue by TimWillis** [Polymer/vulcanize#243]
I use vulcanize  --strip-comments -p "../" layout/layout.html > build/layout.html  
with no errors, but when I use vulcanize  --strip-comments -p "../" layout/layout.html > build/layout.html  --inline-css --inline-scripts
I get wrong path errors for the scripts/css it is trying to inline.

**Comment by azakus** [comment]
Duplicate of #244
