### ISSUE TITLE
Inline Scripts/CSS Error

### ISSUE THREAD

**Issue by bhsnll** [Polymer/vulcanize#244]
In version ```1.10.1``` everything works just fine but when I update to any version after that I begin to see problems. This is my input:
```
vulcanize -p "." Components/dvr-manager/dvr-manager.html > whatever.html --inline-scripts
```

This is the error I get:
```
{ [Error: ENOENT, open 'c:\projects\byutv2\Webs\Cms.Web\projects\byutv2\Webs\Cms.Web\null\bower_components\web-animations-js\web-animations-next-lite.min.js']
   errno: -4058,
   code: 'ENOENT',
   path: 'c:\\projects\\byutv2\\Webs\Cms.Web\\projects\\byutv2\\Webs\\Cms.Webs\\null\\bower_components\\web-animations-js\\web-animations-next-lite.min.js' }
```

It looks like its creating the path to the file incorrectly. It repeats some portions of it and even throws a ```null``` in there. This happens the same for the ```--inline-scripts``` flag and the ```--inline-css``` flag.

**Comment by azakus** [comment]
You should have a preceding slash to the file path argument, `/Components/dvr-manager/dvr-manager.html`

**Comment by bhsnll** [comment]
Using version ```1.10.1``` or version ```1.10.2``` when I put a slash in front:

![g3009](https://cloud.githubusercontent.com/assets/10457862/10006468/ac9d80dc-607a-11e5-902e-461062ef5f5b.png)

Using version ```1.10.1``` without a slash in front it works.

With version ```1.10.2``` without a slash in front:

![g3944](https://cloud.githubusercontent.com/assets/10457862/10006591/af170b52-607b-11e5-9374-15d36935cc53.png)

I don't think the slash is the problem. I think the error has to do with something introduced between versions ```1.10.1``` and ```1.10.2```.

**Comment by azakus** [comment]
Hmm, what shell are you using on windows? Does it try to handle the path separator differences between windows and unix for you? That may be breaking the path handling.

**Comment by bhsnll** [comment]
Git bash from https://git-scm.com. I don't really know about the path separator differences. Right now I'm just using the older version of vulcanize because its working for me and I need to get my current project done. I may look more into why I'm having problems with the newer version if I find some time.

It looks like the problem I'm having might be the same as what's recorded in this issue: https://github.com/Polymer/vulcanize/issues/243.

**Comment by azakus** [comment]
Found the issue, style and script inlining assumes unix paths in one spot. #243 and this are the same issue.

**Comment by bhsnll** [comment]
Great! Works perfectly.
