### ISSUE TITLE
Remove Unused Imports

### ISSUE THREAD

**Issue by phidias51** [Polymer/vulcanize#258]
Components have a tendency to evolve over time, and we often end up with imports for elements that are no longer used in the component.  It would be great if there was a way to strip unused imports from a component file.  You'll find a conversation with a potential solution here: https://plus.google.com/+MarkFortner/posts/QhjCEEfqEaB

**Comment by ebidel** [comment]
I've been wondering the same thing and often run into this issue when developing. You add/remove components and it's hard to know what's what.

I'm not sure vulcanize (build time) is the right tool for the job though. There are cases where you don't create element right away (later declare them or use `document.createElement`). The imports are still needed for these scenarios. So a runtime extension/tool might be more useful?

I created a bookmarklet to catch missing html imports: https://gist.github.com/ebidel/cea24a0c4fdcda8f8af2#file-unregistered_custom_elements-bookmarklet-js

It's very handy for knowing why an element isn't work...b/c you've missed loading it import! I wonder if the opposite would be useful? That is, a bookmarklet that reports what elements polymer has registered but could not be found on the page?

**Comment by phidias51** [comment]
At the moment I'm going through each of my components looking for unused imports.  And it's a rather painstaking task to do.  We're trying to cut down on initial load time.  

Early on in the project we ran into the problem you're alluding to, but now missing imports are the first thing we check whenever things go awry with an element.  

Either way as a runtime tool in Chrome Dev Tools, or a vulcanize plugin, it would be useful to have these tools.

**Comment by azakus** [comment]
Maybe this is a better job for [polylint](https://github.com/polymerlabs/polylint), our new linting tool. @garlicnation: wdyt?

**Comment by ebidel** [comment]
I created a bookmarklet that kind of does this. It's not perfect but using it just now, I discovered I was loading paper-card.html when I didn't need it!

https://gist.github.com/ebidel/9249cf3d1504fb119356

**Comment by ebidel** [comment]
@phidias51 LMK if that bookmarklet is useful. @justinfagnani might also take a feature request in the extension we're working on :) https://github.com/PolymerLabs/polydev/issues

**Comment by justinfagnani** [comment]
I think polylint is there right tool. The extension should be for runtime tooling, where the hydrolysis based tools are for static tooling.

Polylint might need a way to suppress a warning if an element is only created dynamically though.

**Comment by indolering** [comment]
I read this and immediately thought of Polylint, vote to close.

**Comment by ebidel** [comment]
Closing for https://github.com/PolymerLabs/polylint/issues/37
