### ISSUE TITLE
`excludes` doesn't accept RegExp[] as described in the readme

### ISSUE THREAD

**Issue by justin-lau** [Polymer/vulcanize#266]
I am new to Polymer and I'm trying to use [broccoli-vulcanize](https://github.com/mbykovskyy/broccoli-vulcanize) in my Ember.js app. I was really confused when I tried to compile with the example setting and it failed.

After spending some time digging around the source code of broccoli-vulcanize and vulcanize, it appears to me that vulcanize had changed the argument type for `excludes` from an Array of `RegExp` objects to an Array of String, without bumping the major version to reflect a breaking change.

I think the [readme](https://github.com/Polymer/vulcanize#using-vulcanize-programmatically) should really be updated to reflect the changes.

**Comment by franzliedke** [comment]
I encountered this problem, too. Just sent a PR (#282) noting this in the readme.
