### ISSUE TITLE
Why does my vulcanized page not show in IE when using webcomponents-lite.js

### ISSUE THREAD

**Issue by JustinCase1089** [Polymer/vulcanize#276]
Hi

I have made a somewhat simple example that illustrates my problem and asked here 

https://stackoverflow.com/questions/33495689/in-polymer-1-0-why-does-my-vulcanized-page-not-show-in-ie-when-using-webcomponen

hoping its just an issue from my side. But it seems that vulcanize and webcomponents-lite does not play well together in IE. 

Unless I have done something silly, then I believe this is a bug

Thanks :-)

**Comment by rubenstolk** [comment]
Most likely https://github.com/Polymer/vulcanize/issues/223 which goes unresolved till date... As usual, nobody cares about IE, which hurts when it has to work :(

**Comment by JustinCase1089** [comment]
End users care and are expecting it to work. Sure hope I am not being caught between a rock and a hard surface.

**Comment by rubenstolk** [comment]
I feel with you! I'm investigating why `polymer-starter-kit` is not facing this issue, was hoping that @azakus or @addyosmani can shed some light here...

**Comment by gertcuykens** [comment]
Have the same problem, need some priority here, we are talking about a significant portion of windows 10 users, and I can't blame them for not being up to date this time...

**Comment by JustinCase1089** [comment]
@rubenstolk any luck on your investigations?

**Comment by rubenstolk** [comment]
@JustinCase1089, this is solved in last version of webcomponentsjs, see the issue I mentioned earlier.

This issue can be closed...
