### ISSUE TITLE
Optionally remove whitespace during vulcanization of css

### ISSUE THREAD

**Issue by samccone** [Polymer/vulcanize#283]
> 
As the vulcanize process inlines the JS and CSS for elements, the resulting elements.vulcanized.html contains several hundred KB of empty space. By using gulp-minify-inline on the vulcanized file, the size goes from 447K down to around 267K for the default install. Even with gzipped calls, this can be quite a bit of pageload reduced.

ref:
https://github.com/PolymerElements/polymer-starter-kit/pull/486#issue-115633232
https://github.com/PolymerElements/polymer-starter-kit/issues/564
https://github.com/PolymerElements/polymer-starter-kit/pull/565

**Comment by ebidel** [comment]
I think the idea was to [remove this kind of feature](https://github.com/Polymer/vulcanize#what-happened-to-feature-from-0x) from vulcanize and have other tools like Polyclean [that do the minification](https://github.com/PolymerLabs/polyclean/blob/master/index.js#L136) In the past, we've ran into many issues with css/html minifiers mucking output.

**Comment by garlicnation** [comment]
@ebidel is correct. This might be a feature we'd consider including in [Polytool](https://github.com/Polymer/polytool), however.

**Comment by samccone** [comment]
I have reopend over in polytool land as to not loose track of this valid issue
