### ISSUE TITLE
vulcanize alters script execution order unexpectedly

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/vulcanize#284]
vulcanize (1.12.3) unexpectedly alters the order of script execution if an imported document has a script in the `<body>`. Example: http://pastebin.com/raw.php?i=1BPLc5iA

The unvulcanized `in.html`will run the first script first, but loading the output of `vulcanize in.html` will run the second script first.

Is this expected behavior, or a bug?

**Comment by ebidel** [comment]
Typically we don't put a full html document in an import. For example, you have `<html>`, `<body>`, etc first.html. So I believe vulcanize is preserving that relationship for you. first.html should really just be: ```<script>"First"</script>```

**Comment by azakus** [comment]
The relationship should be that scripts in an import execute in the order they are defined, so this feels like a bug to me.

**Comment by mgiuffrida** [comment]
ebidel: **typically** you don't put a full html document in an import, but in PolymerLabs/crisper#29 you just said:

>HTML Imports are just HTML documents. In your example, someone can import out.html and use your element just as they could before. I don't understand what you mean by they "all think they're root files". HTML import documents are separate from the main page, even if they contain all the stuff in out.html.

So: **Typically** you don't put a full html document in an import, but it's still valid to do so (and crisper does!). Yet vulcanize will reorder scripts when the imports are full html documents (ie, those produced by crisper).

Based on what you've said, logically at least this issue *or* that issue must be a bug.
