### ISSUE TITLE
HTML <base> tag

### ISSUE THREAD

**Issue by redbassett** [Polymer/vulcanize#287]
I am trying to use Vulcanize (via Polybuild) to build a Polymer app for distribution with Gulp. The `index.html` file is located in `dist/`. The `webcomponents.min.js` file it needs is inside `dist/bower_components/webcomponentsjs/`, and is referenced inside `index.html` with an import:

    <script src="bower_components/webcomponentsjs/webcomponents.min.js"></script>

`index.html` also has a `<base href="/">` tag in its `<head>`.

When the Vulcanize Gulp task is run, the following error is displayed:

    Error in plugin 'gulp-vulcanize'
    Message:
        ENOENT, open '/.index.html/bower_components/webcomponentsjs/webcomponents.min.js'
    Details:
        errno: -2
        code: ENOENT
        path: /.index.html/bower_components/webcomponentsjs/webcomponents.min.js
        fileName: /Users/<username>/Documents/<project>/dist/index.html

If run from the command line (on the `index.html` file), no error is displayed (since no file read is attempted), but the script import is replaced with the following:

    <script src="../../../../../.index.html/bower_components/webcomponentsjs/webcomponents.min.js"></script>

This seems to indicate that Vulcanize is taking `<base href="/">` to mean that it should use the computer's root as the root path, as commenting out the `<base>` tag solves the issue completely.

**Comment by garlicnation** [comment]
Setting the root directory for the build with `--abspath` will allow you to use `<base>` without issue.

See https://github.com/Polymer/vulcanize#options
