### ISSUE TITLE
Vulcanize polymer, iron-elements, paper-elements in the same time not working

### ISSUE THREAD

**Issue by andrew-vandenbrink** [Polymer/vulcanize#313]
Gulp Task
```
paths.vulcanDst = paths.webroot + "engine/bundle/vulcan/";
gulp.task('vulcanize', function () {
    return gulp.src([
paths.webroot + "lib/polymer/polymer.html", 
paths.webroot + "lib/iron-elements/iron-elements.html", 
paths.webroot + "lib/paper-elements/paper-elements.html"
])
      .pipe(vulcanize({
          stripComments: true,
          inlineScripts: true,
          inlineCss: true
      }))
      .pipe(crisper())
      .pipe(gulp.dest(paths.vulcanDst));
});
```
Produce very strange files
![image](https://cloud.githubusercontent.com/assets/12871379/13485646/44f900a8-e10a-11e5-8b75-e97756e5d17d.png)

especially iron-elements.js

When i try to use vulcanized elements
![image](https://cloud.githubusercontent.com/assets/12871379/13485703/ca6047e2-e10a-11e5-8b94-695453477b4d.png)

**Comment by garlicnation** [comment]
If you want to build 3 seperate but compatible components, you'll have to build them using --excludes.

See the polymer build: https://github.com/Polymer/polymer/blob/master/gulpfile.js#L68
