### ISSUE TITLE
Latest version of hydrolysis broke vulcanize inlineScripts verification

### ISSUE THREAD

**Issue by Rastikko** [Polymer/vulcanize#319]
Looks like now the default behavior of vulcanize is to inline the scripts in the file. If you lock the version of hydrolysis to 1.22 does not happen any more.

Apparently this PR caused the issue: https://github.com/Polymer/hydrolysis/pull/233

**Comment by brandonbuttars** [comment]
OMG.  You are my hero for figuring this out.  This freaking broke my deployment process.  Used shrinkwrap to lock the version down.  http://www.asyncdev.net/2012/08/locking-node-js-module-versions-with-shrinkwrap/
