### ISSUE TITLE
Vulcanize rearranges script tags which breaks things

### ISSUE THREAD

**Issue by AshleyScirra** [Polymer/vulcanize#325]
Files for repro: https://dl.dropboxusercontent.com/u/15217362/vulcanizebug.zip

If you vulcanize an import that looks like this:

```
<script src="before.js"></script>
<link rel="import" href="nested.html" />
<script src="after.js"></script>
```

You get output that looks like this:

```
<script src="after.js"></script>
<script src="before.js"></script>
```

Obviously since after.js depends on things defined in before.js, it breaks. So vulcanize ends up mangling the order of scripts and breaks things.

**Comment by danbeam** [comment]
it looks like this might be affecting Chrome's UI as well.

@AshleyScirra you can ~~hack~~work around this ([like we are in Chrome](https://codereview.chromium.org/1846383002/)) by just making everything a `<link rel=import>`.

/cc @tjsavage @garlicnation @azakus
