### ISSUE TITLE
Vulcanize produces repeated scripts

### ISSUE THREAD

**Issue by jiettu** [Polymer/vulcanize#327]
I have created two Polymer custom elements. Both of them uses moment.js. So I have referenced it in both the elements, like:``` <script src="../../bower_components/moment/min/moment.min.js"></script>```
I use vulcanize to produce a single import file element.html. The issue is that the content of moment.js appears twice in the vulcanized file. Is this correct? Is there a way to avoid it?

**Comment by TimvdLippe** [comment]
Common practice is to wrap the library you are loading into an element. An example of such an element is https://github.com/bendavis78/moment-element/blob/master/moment-import.html
