### ISSUE TITLE
1.14.9 fails on Windows

### ISSUE THREAD

**Issue by kwaclaw** [Polymer/vulcanize#332]
Older version 1.14.8 works, but new version 1.14.9 returns:
ERROR finding /Work/QLine/WebClients/AppPortal/elements/bower_components/bower_components/bower_components/bower_components/web-animations-js/web-animations-next-lite.min.js

There is a package neon-animation which references web-animations-js.

**Comment by davidlwatsonjr** [comment]
+1 Getting the same issue

**Comment by dudabone** [comment]
+1 Same issue on Mac

**Comment by xwsxethan** [comment]
+1 Same issue on ubuntu

**Comment by govis** [comment]
Same here. In my case  I have a local element in project\component folder (not in bower_components) that links <code>../bower_components/paper-dialog/paper-dialog.html</code> and it ends up looking for <code>project\component\bower_components\paper-dialog\import\neon-animation\import\neon-animation\import\web-animations-js\web-animations-next-lite.min.js</code>

**Comment by ElsewhereGames** [comment]
This is a really bad since gulp-vulcanize will automatically get the latest 1.14.x version of this tool.

**Comment by azakus** [comment]
Working on it

**Comment by azakus** [comment]
Unpublished v1.14.9 until I can get to the bottom of the breakage.
