### ISSUE TITLE
Running v1.14.11 never completes

### ISSUE THREAD

**Issue by jeffposnick** [Polymer/vulcanize#336]
I'm seeing this behavior on OS X 10.11.4 and Node v5.9.1.

When using the CLI v1.14.8 (the previous version published to `npm`), everything worked as expected. Using the just-released v1.14.11, the `vulcanize` command run against the same source HTML never completes, and as per the `top` command, `node` ends up pegging one my CPUs at 100% indefinitely.

I'm unfortunately not sure what `vulcanize` is doing, but if there's any specific debugging steps you'd like me to take, I'd be happy to do that. The source HTML that I'm vulcanizing is part of a private project, but I can pass that along out of band if you're not able to reproduce.

**Comment by arturparkhisenko** [comment]
v1.14.8 vs v1.14.11 on (i7-4790K) :smiling_imp::
![vulcanized-test-v1 14 11](https://cloud.githubusercontent.com/assets/139212/14452973/a563c824-009a-11e6-99c1-e2ab6ec98c40.png)

**Comment by kwaclaw** [comment]
Same here, on Windows, CPU at 100%. Maybe infinite loop:?

**Comment by jonnenauha** [comment]
Same in our build server, 100% on one CPU.

```Ubuntu 14.04.4 LTS, Linux 3.19.0-30-generic x86_64```

**Comment by jonnenauha** [comment]
Looks like https://github.com/Polymer/grunt-vulcanize/blob/v1.0.0/package.json wants `"vulcanize": "^1.9.3"`.

Not that familiar with the ^ notation in node. I assume it can upgrade to whatever minor version then like 1.14? Always thought that would mean that the patch can only be upgraded.

**Comment by xwsxethan** [comment]
+1 Same issue on ubuntu and running on Travis CI as part of our CI process.

**Comment by jeffposnick** [comment]
If folks are using `gulp-vulcanize` and don't have direct control over which version of `vulcanize` gets pulled in, you can create an `npm-shrinkwrap.json` file to force `v1.14.8`, which still works. (Hat tip to http://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions)

```json
{
  "dependencies": {
    "gulp-vulcanize": {
      "version": "6.1.0",
      "dependencies": {
        "vulcanize": {
          "version": "1.14.8"
        }
      }
    }
  }
}
```

I'm sure a similar approach would work with `grunt-vulcanize` or the other wrappers.

**Comment by azakus** [comment]
Thanks for the reports. I think there may be an unexpected quadratic operation now. I'll take a look!
