### ISSUE TITLE
Is Hydrolysis specified as a loader by default?

### ISSUE THREAD

**Issue by avizcaino-newuibcn** [Polymer/vulcanize#340]
Even I'm generating my vulcanized file (with a gulp task) as follows: 

```
return gulp.src(paths.src + '/elements.html')
    .pipe(exec('vulcanize <%= file.path %> -o ' + paths.src + '/polymer.html --csp --inline --strip'))
    .pipe(exec.reporter(reportOptions));
```

and I'm not specifying a loader, later on, when the app is running, I can see that hydrolysis is called: 
![captura de pantalla 2016-05-03 a les 13 36 55](https://cloud.githubusercontent.com/assets/9590299/14982115/2bbb655e-1134-11e6-8d94-3b7d3cb1420f.png)

This is slowing my app startup since needs to load almost 5mb because of Hydrolysis...

I'm quite lost with this issue. Is Hydrolysis strictly mandatory? Is there any way to disable it?

**Note:** I'm using Webpack and aurelia-polymer plugin.

**Comment by ebidel** [comment]
What does elements.html look like? Hydrolysis isn't needed by the elements. It's only used
by `iron-component-page`, so if you're vulcanizing that...don't :)

**Comment by avizcaino-newuibcn** [comment]
Thanks! I was vulcanizing iron-elements and paper-elements. Just vulcanizing paper-elements solved the hydrolysis problem but now I'm having `regeneratorRuntime is not defined`. I'll keep looking to solve this but thanks!

**Comment by avizcaino-newuibcn** [comment]
Solved! Hydrolysis was importing `babel-regenerator-runtime`. I just had to import `babel-polyfill` on my code again and the problem is solved.

Thanks!
