### ISSUE TITLE
Doesn't work with Polymer-cli element structure

### ISSUE THREAD

**Issue by jaichandra** [Polymer/vulcanize#356]
If I create a polymer-cli element project where dependencies are mapped relative to 'bower_components' folder like below,
<link rel="import" href="../polymer/polymer.html"> or 
<link rel="import" href="../paper-button/paper-button.html">,
vulcanize fails to find the file. 

How can I use vulcanize with this structure? Or should I not be using vulcanize if I am using polymer-cli?

**Comment by justinfagnani** [comment]
Use `polymer build`, it sets up and calls vulcanize correctly.

**Comment by jaichandra** [comment]
I am using an element project. I guess ```polymer build``` is only for app projects. I tried running build on the element project and it failed.
