### ISSUE TITLE
Style includes in base document need to be reordered

### ISSUE THREAD

**Issue by rictic** [Polymer/vulcanize#357]
`index.html`

``` html
<head>
<link rel="import" href="bower_components/polymer/polymer.html">
<link rel="import" href="dep.html">
<style is="custom-style" include="foo"></style>
</head>
<body>
<div>
  hello
</div>
</body>
```

`dep.html`

``` html
<dom-module id='foo'>
  <template>
    <style>
      div {
        color: red;
      }
    </style>
  </template>
</dom-module>
```

When unvulcanized the `<style include>` in index.html comes after the `<link import>`, and so the include is able to resolve and the body text is red.

Vulcanization however produces this:

`vulcanized.html`

``` html
<html><head><meta charset="UTF-8">
<style is="custom-style" include="foo"></style>
</head>
<body><div hidden="" by-vulcanize="">

<!-- ...snip contents of polymer.html... -->

<dom-module id="foo" assetpath="/">
  <template>
    <style>
      div {
        color: red;
      }
    </style>
  </template>
</dom-module>
</div>
<div>
  hello
</div>
</body></html>
```

Now because the style include comes _before_ the style module it's including, the body text is unstyled.

I believe the correct thing to do here would be to move all styles, or at least all style includes, from the main document so that they're located after the end of the inlined documents.

**Comment by maxiplay** [comment]
+1 its break my style on firefox

**Comment by Bubbit** [comment]
It seems to be related to this change: https://github.com/Polymer/vulcanize/commit/4511f01bd23e27edd407c443ec2630ef91a6ee25#diff-2fd25663c1d3dca2153ce60dac0f7245R179

**Comment by usergenic** [comment]
Vulcanize 1.15.1 released.  Should fix this.
