### ISSUE TITLE
Vulcanize moves non-import link tags from head to body in the main document

### ISSUE THREAD

**Issue by Caffeinix** [Polymer/vulcanize#398]
Given the following document:

```html
<!doctype html>
<html>
<head>
  <link rel="icon" href="/favicon.ico">
  <link rel="manifest" href="manifest.json">
</head>
<body>
</body>
</html>
```

Running vulcanize will output something like:

```html
<!doctype html>
<html>
<head></head>
<body>
  <div hidden by-vulcanize>
    <link rel="icon" href="/favicon.ico">
    <link rel="manifest" href="manifest.json">
  </div>
</body>
</html>
```

This is due to the code at [lib/vulcan.js:230](https://github.com/Polymer/vulcanize/blob/master/lib/vulcan.js#L230), which uses [a predicate](https://github.com/Polymer/vulcanize/blob/master/lib/vulcan.js#L179) to select all elements with tag name `link` or `script` (regardless of attributes) and moves them into the body.  Unfortunately, applying that transformation causes neither the favicon nor the manifest to be detected by the browser.

**Comment by usergenic** [comment]
This looks like it was fixed by that merge, so closing.
