### ISSUE TITLE
Support rewriting dependencies

### ISSUE THREAD

**Issue by arthurevans** [Polymer/vulcanize#41]
For the polymer web site, it would be nice to be able to generate a set of vulcanized files, each consolidating a set of vulcanized files, something like this:

base.html includes a.html, b.html
more-stuff.html includes c.html, d.html which depends on a.html
extra-stuff.html includes e.html, which depends on b.html and d.html

It would be good to load a minimal set for the landing page, and load other stuff as needed. However, since it's a one-page app, all the imports need to work together.

I know doing this in an automated fashion would be complicated. My simplistic proposal for a manual process is something like this:

vulcanize -o base.html base-imports.html --map base.map

Where base.map contains a list of dependencies included in base.html

Then:

vulcanize -o more-stuff.html more-stuff-imports.html --depends-on base.html --map more-stuff.map

Where any reference to an import in base.map is replaced with an import of base.html.

Feel free to propose a more elegant mechanism ;-).

**Comment by azakus** [comment]
This should be handled by bundles, which is in-progress.
