### ISSUE TITLE
Sending output to stdout if no output file specified

### ISSUE THREAD

**Issue by JPedersen** [Polymer/vulcanize#46]
Hi!

Reading the [docs](http://www.polymer-project.org/articles/concatenating-web-components.html):
"If no output is specified, vulcanized.html is used by default."

Are there any plans on changing this to the standard behaviour of sending the output to stdout instead? I can't see the benefit of creating a non-standard file instead.

At the moment it's hard to build vulcanize into a existing build system without it.

Thanks,
Josua

**Comment by azakus** [comment]
This is the only output of `vulcanize` in 1.x
