### ISSUE TITLE
Building a polymer project with Vulcanize, ensuring file paths resolve when copied from /app to /dist

### ISSUE THREAD

**Issue by benjaminapetersen** [Polymer/vulcanize#51]
Greetings!

I had a question rolling on Twitter that @addyosmani graciously responded to.  He suggested I file a bug here so it can be better processed. I'm working with Vulcanize to do a fairly typical app build process and end up with a /dist folder that is ready to deploy.  The problem is that when I run Vulcanize I end up with files that have references back to my /app folder.

I'm building an app that follows fairly typical patterns you see with Yeoman nowadays.  The structure looks like this:

```
- app
  - components  
    - polymer
    - platform
    - my-component-1
    - my-component-2
  - index.html
  - foo.html
- build
- dist
- nginx
- etc.
```

I have just started using Vulcanize via the gulp-vulcanize plugin.  I'm trying to figure out how to build/deploy by vulcanizing my /app/*.html files, moving them to /dist, and having /dist/components include the needed files.  

My gulp task is simple at this point:

```javascript
// trimmed down for clarity:
var bases = {
  app: '/app',
  dist: '/dist'
}

gulp.task('vulc', function() {
  gulp.src(bases.app+'*.html')
    .pipe(vulcanize({
      dest: bases.dist
      // strip: true
      // csp: true
    }))
    .pipe(gulp.dest(bases.dist))
});

```
This is definitely cool, but in my /dist/index.html file I will have references like this:

```
<img class="icon icon-{{message.sender}}" src="../app/components/my-conversations/unknown.gif"
 

<polymer-element name="my-message-receiver" attributes="eventType" assetpath="../app/components/my-message-receiver/">


```

The ../app/components/* references is what is confusing to me.  I must admit that I am new to Polymer as of the past few weeks, and Vulcanize as of yesterday so Its entirely possible that I'm just not doing something right.  The ideal is something like /dist/components/* with all the necessary dependencies copied over & file paths resolved there.  Trying to think through how that fits with the csp & inline flags.  

It makes sense that the job of Vulcanize is just to process your Polymer components and not care about other dependencies & resolving all your paths.  I'm trying to solve a problem similar to how usemin would facilitate processing assets in a typical angular or other js app:

```javascript
// sample straight from https://github.com/zont/gulp-usemin which illustrates how 
// to orchestrate the build process and end up with a /build/ directory that is 
// ready to deploy.
gulp.task('usemin', function() {
  gulp.src('./*.html')
    .pipe(usemin({
      css: [minifyCss(), 'concat'],
      html: [minifyHtml({empty: true})],
      js: [uglify(), rev()]
    }))
    .pipe(gulp.dest('build/'));
});
```

Hopefully this is thorough enough to be helpful.  I'm happy to expand on anything that is unclear.  Thanks!

**Comment by vossad01** [comment]
+1

**Comment by benjaminapetersen** [comment]
I'm still looking to come back to this soon and tinker some more.

**Comment by jmorille** [comment]
+1 A solution should be very usefull for use it in real project
