### ISSUE TITLE
inline and csp options are confusing

### ISSUE THREAD

**Issue by truiken** [Polymer/vulcanize#56]
The documentation for the --inline option states that it is "the opposite of CSP mode."  To me that reads that they are mutually exclusive, but they're not, because the next 'option' is "--inline --csp
Bundle all javascript (inline and external)"

Perhaps a new option name for the latter would be more clear, or --csp can be a multi-valued option, e.g., "--csp=inline,external".

**Comment by azakus** [comment]
CSP has been split out to `crisper` in 1.x
