### ISSUE TITLE
vulcanize's semicolon-insertion breaks source maps

### ISSUE THREAD

**Issue by ajklein** [Polymer/vulcanize#64]
Source maps are of the form:

```js
//# sourceMappingURL=polymer.js.map
```

But that gets translated to

```js
//# sourceMappingURL=polymer.js.map;
```

by vulcanize, resulting in devtools attempting to load "polymer.js.map;". I'd suggest avoiding inserting semicolons at the end of comments.

**Comment by azakus** [comment]
This functionality was moved to crisper, moving the issue there as well.
