### ISSUE TITLE
Option to download and inline remote sources

### ISSUE THREAD

**Issue by azakus** [Polymer/vulcanize#8]
Evaluate some sort of `--remote` option that will grab script and stylesheets with absolute, remote URLs.

**Comment by azakus** [comment]
Nah, this is a giant rathole of complexity.

**Comment by rajsite** [comment]
@azakus Happen to remember some of the complexities of doing this?

I've been writing some jsbins relying on polygit.org and unpkg.com and was wondering if I could use vulcanize to make "builds" that could be used offline (ie intranet).

It really shrinks the getting started window for new users. Don't have to start with huge amounts of tooling to get quick results :)

**Comment by justinfagnani** [comment]
One problem here is that it starts turning Vulcanize into a sort-of package manager. Users would be much better off using Bower to install packages locally than relying on a much less complete feature in Vulcanize.
