### ISSUE TITLE
Option to output just a single html import file containing all templates

### ISSUE THREAD

**Issue by krisnye** [Polymer/vulcanize#86]
I need to use the web components programmatically.  I don't want the output to be a stand alone html page.  I want it to just contain all of the web components that I will need.  This way, I can use an html import on the resulting file and then instantiate any of the contained web controls via javascript.

**Comment by alixeb** [comment]
Would this change also involve passing html as a string to be processed?

i.e if you use Flux/React your server code output html as a string, that you then want to feed to vulcanize and get back a string that you can then send as type html.

Or should I create a separate issue/improvement for that scenario?

**Comment by eximius313** [comment]
We also need functionality of importing single html file containing all components in it.
It would be awesome to have possibility to import it like that:
```
<script type="text/javascript" src="components/webcomponentsjs/webcomponents-lite.min.js"></script>
<link rel="import" href="components/all-vulcanized-components.html")">
```

**Comment by joineral32** [comment]
Any particular reason why this issue ended up abandoned/closed? Not having this feature seriously limits Polymer's utility in a server-side templated application. I'm using Express with Handlebars to render our different views' HTML, and using Polymer elements as tags in that rendered HTML to allow us to spit out a page that features rich UI components. Vulcanize is not useful for that purpose, and I really don't like the idea of pulling in all those components individually...
