### ISSUE TITLE
Make exclusion similar to r.js

### ISSUE THREAD

**Issue by robdodson** [Polymer/vulcanize#88]
In [r.js](http://requirejs.org/docs/optimization.html) when you're creating module bundles you can tell one bundle to exclude everything that's in another bundle. [Here's an example](https://github.com/robdodson/requirejs-multipage-shim-boilerplate/blob/master/options.js#L6). I'm creating 3 bundles (`common`, `main-about`, `main-contact`). Instead of having to manually go through everything in `common` to find all of the dependencies and exclude each as a regex, I can just tell the `main-about` and `main-contact` bundles to [exclude all of the modules in `common`](https://github.com/robdodson/requirejs-multipage-shim-boilerplate/blob/master/options.js#L27). This makes it very easy to lazy load AMD bundled modules and I think imports could use a similar approach.

**Comment by azakus** [comment]
Vulcanize 1.x exclusion includes transitive dependencies via hydrolysis.

**Comment by amitnavale** [comment]
:) now I am running into an issue which I guess you guys have envisioned earlier. 
I really like the idea of  excludes: ['foo.vulcanized.html', 'bar.vulcanized.html'].  
Do we have this implemented yet?
