### ISSUE TITLE
<base href> tag should be respected when loading resources

### ISSUE THREAD

**Issue by bendavis78** [Polymer/vulcanize#94]
If an html file defines a <base href> tag, all resource paths on that page should be interpreted as relative to that path.

For example:
```html
<html>
  <head>
    <base href="../../foo/bar">
    <script src="baz/qux.js"></script>
  </head>
</html>
```
When vulcanize loads this file (eg, during a --csp --inline build), it wil fail because "baz/qux.js" does not exist relative to the html file. The path should instead be translated with regard to the base href.

**Comment by AEtherSurfer** [comment]
I think this broke <base target="_blank"/>

**Comment by hawkett** [comment]
With a folder structure like:

```
/foo
   /index.html
/bar
   /my-element.html
```

URL in the address bar is ```/foo/index.html```

index.html specifies:
* ```<base href="/foo/" target="_blank">```
* ```<link rel="import" href="../bar/my-element.html">```

This works fine in Chrome/Firefox/Safari without vulcanization, but breaks during vulcanization with: ```Error: ENOENT, open '/foo/bar/my-element.html'```

The reason for doing this in my case is that I want *any* path beginning with ```/foo/``` (e.g. ```/foo/users/1/profile```) to serve up index.html, and I then use page.js *without hashbang* to treat ```users/1/profile``` as a route in my SPA.

Worth noting that the href attribute in ```<base>``` [must be absolute](http://www.w3.org/TR/html-markup/datatypes.html#common.data.uri.absolute-def) - so the href in the original post is not technically valid as far as I read it.
