### ISSUE TITLE
Vulcanize with parse5 removing closing polymer-element

### ISSUE THREAD

**Issue by robdodson** [Polymer/vulcanize#96]
When I run the latest version of vulcanize against [this file](https://github.com/robdodson/its-hackademic/blob/master/static/imports.html#L397) it strips out the closing `</polymer-element>` on `user-credentials`. This causes Polymer to hang until I tell it to `forceReady`. Switching to `vulcanize` 0.4.3 fixes the issue. I'm wondering if the culprit is parse5?

**Comment by azakus** [comment]
Is this still an issue in 0.7.5?
