### ISSUE TITLE
document._currentScript.ownerDocument does not work with --csp flag

### ISSUE THREAD

**Issue by ebidel** [Polymer/vulcanize#98]
To setup default values for bindings in `<core-style>`, we recommend getting the current import via:

    var thisDoc = document._currentScript.ownerDocument;

This doesn't work with `--csp`flag  because the `ownerDocument` is not the import. Not sure if vulcanize should somehow rewrite this, but it's definitely a gotcha.

**Comment by azakus** [comment]
Nor will it ever :(
