### ISSUE TITLE
Most node tools treat -v as the shorthand for --version, rather than --verbose

### ISSUE THREAD

**Issue by Pomax** [Polymer/vulcanize#99]
For node CLI utilities the `-v` shorthand flag is treated as a version request (see bower, browserify, npm, gulp, node, etc) rather than a shorthard for --verbose. It might be a good idea to change the binding so that vulcanize behaves the same way when called as `vulcanize -v`.

**Comment by azakus** [comment]
Implemented `-v` as `--version` in 1.x
